### ISSUE TITLE
2Q

### ISSUE THREAD

**Issue by iraniamir** [expo/expo-three#1]
Hi there, if i use this library there is no problem for publishing app in apk ?
and next im looking for human body to move in 360dig and its possbile to define some parts on body for click and see alert ?!
thanks

**Comment by dikaiosune** [comment]
Hi! AFAIK, you'd only use this library if you're already using Expo, which has a service for building APKs: https://docs.expo.io/versions/v19.0.0/guides/building-standalone-apps.html

I think the second part of your question is probably a better fit for the [three.js tag on StackOverflow](https://stackoverflow.com/questions/tagged/three.js). Thanks!
