### ISSUE TITLE
createTextureAsync from remote dynamic image file

### ISSUE THREAD

**Issue by ericmorgan1** [expo/expo-three#10]
Images can be loaded as a material using code like the following:

```
const img = require('./assets/images/myImage.jpg'); 
const material = new THREE.MeshBasicMaterial({
   map: await ExpoTHREE.createTextureAsync({
     asset: Expo.Asset.fromModule(img),
   })
});
```

How can we create a material from a remote file determined at runtime (where `require() `is not available) and we cannot create an `Expo.Asset`?

Here are some attempts I've made, with no luck:

```
var expoAsset = new Expo.Asset();
expoAsset.uri = "https://s3.amazonaws.com/exp-brand-assets/ExponentEmptyManifest_192.png";
const material = new THREE.MeshBasicMaterial({
   map: await ExpoTHREE.createTextureAsync({
     asset: expoAsset
   })       
});


var textureLoader = new THREE.TextureLoader();
textureLoader.load("https://s3.amazonaws.com/exp-brand-assets/ExponentEmptyManifest_192.png", function(loadedTexture) {     
  const material = new THREE.MeshBasicMaterial({ map: loadedTexture });
});  


var loadingManager = new THREE.LoadingManager();
var imageLoader = new THREE.ImageLoader(loadingManager);
imageLoader.load("https://s3.amazonaws.com/exp-brand-assets/ExponentEmptyManifest_192.png", function(image) {
    var texture = new THREE.Texture();
    texture.image = image;
    var material = new THREE.MeshBasicMaterial( {map: texture});        
});
```

**Comment by EvanBacon** [comment]
@ericmorgan1 just pushed `expo-three`: 2.0.7.

**You can now call:**
```js
const someRemoteUrl = "https://avatars2.githubusercontent.com/u/9664363?s=88&v=4"
const texture = await ExpoTHREE.loadAsync(someRemoteUrl)
```

**Comment by ericmorgan1** [comment]
@EvanBacon Thank you for the fast turnaround! Works great! : )

**Comment by EvanBacon** [comment]
@softnodelabs I really cannot reproduce your error. Could you please reproduce the error in a snack?

**Comment by softnodelabs** [comment]
@EvanBacon I copied your sample code to this snack:
https://snack.expo.io/@softnodelabs/expo-three-remote-image

I get only a white screen.

My testing device: Samsung Galaxy S6 - Android 7.0
I don't have an iOS device so I don't know if this is an Android only issue.

The strange thing is: I changed the code to show a color instead of a texture on the cube and I also got nothing on screen.

I'm really lost on this.

Thanks.

**Comment by EvanBacon** [comment]
@softnodelabs this is an error created on android when you create an `Expo.Asset` from a localUri stored in the `Expo.FileSystem`. This is coming from a function in `expo-asset-utils`, to correct this filp the `Expo.Asset.downloaded` flag and prevent the system from trying to re-download the file! I'll push a version that uses the new `expo-asset-utils` (0.0.3) as soon as I've tested it 💙

**Comment by softnodelabs** [comment]
@EvanBacon I'm happy I can help finding issues. I got everything working. I replicated some of your code in a test project so I could understand how the downloading process and asset creation works. From there I could create a class that works on Android. It needs testing on iOS though.

I don't know if it's needed but as soon as I have the time I can share my code on a snack project.

Thank you!

**Comment by briangainer** [comment]
I have the same error that @softnodelabs had, but I'm on ios. Even after removing all references from the Expo Filesystem in my code, my app still tries to load the old referenced files and gives me an error.

@EvanBacon where do I set the Expo.Asset.downloaded flag?

**Comment by krjk333** [comment]
@EvanBacon , How to load the 3d object like this. I tried with so many methods to load an object. All gets failed.  Please anyone help me to load 3d object in .obj, .gltf, or .glb any of one format in react native.
