### ISSUE TITLE
Is there any harm in using a separate ThreeJS dependency?

### ISSUE THREAD

**Issue by bberak** [expo/expo-three#110]
Hi there,

Thanks for these excellent utils. 

I'm trying to use some of the postprocessing effects and have copied some code from the example. In particular, I have found that the following imports cannot be resolved:

```
import 'three/examples/js/controls/OrbitControls';
require('three/examples/js/postprocessing/EffectComposer');
require('three/examples/js/postprocessing/RenderPass');
require('three/examples/js/postprocessing/ShaderPass');
require('three/examples/js/postprocessing/MaskPass');
```

Using any of the above will yield the typical Unable to resolve module three.../EffectComposer' errors. Perhaps I'm doing something wrong.

That said, if I add the latest version of **three** as a standalone dependency to my package.json (alonside **expo-three**), I can utilize the modular imports from the _jsm_ folder without any issues:

```
import ExpoTHREE from "expo-three";
import suppressExpoWarnings from "expo-three/build/suppressWarnings";
import * as THREE from "three";
import { EffectComposer }  from "three/examples/jsm/postprocessing/EffectComposer";
import { RenderPass } from "three/examples/jsm/postprocessing/RenderPass";
import { UnrealBloomPass } from "three/examples/jsm/postprocessing/UnrealBloomPass";

suppressExpoWarnings();
```
I can confirm that these imports and effects are working just fine. Is there any harm to using **expo-three** just for the utilities, and using a standalone **three** package for all the rendering-related code?

Thanks in advance for your advice!

**Comment by bberak** [comment]
Actually, to anyone else who is thinking about doing this - beware that there are some hairy pitfalls with mixing and matching `import * as THREE from "three";` and `import { THREE } from "expo-three";`.. 

I spent the weekend scratching my head as to why some particle systems were not rendering. Once I referenced the **three** library bundled with **expo-three** (`import { THREE } from "expo-three";`) the problem sorted itself out. It's not an issue of mis-matching versions either, I checked that already.

@EvanBacon would it be possible (and make sense) to not have a hard dependency to **three** but rather add **three** as a peer dependency? That way, we can choose the version of **three** we'd like to use (respecting minimum requirements) and still get all the **expo-three** goodness? I'd be happy to submit a PR.

**Comment by EvanBacon** [comment]
If you submit a PR, please update the Readme to be very clear about the change

**Comment by EvanBacon** [comment]
The hard dependency has been removed

**Comment by bberak** [comment]
Thanks @EvanBacon!
