### ISSUE TITLE
[Regression] v4.0.5+ textures are loaded scrambled.

### ISSUE THREAD

**Issue by murat-mehmet** [expo/expo-three#122]
Awesome lib but since 4.0.5 texture loader is loading images scrambled.
this is the code:
```
        const geometry = new THREE.SphereBufferGeometry(200, 16, 8, 0, 2 * Math.PI, 0, 0.6 * Math.PI);
        geometry.scale(-1, 1, 1);
        const sky = await ExpoTHREE.loadAsync(assets.worlds.sky.space) as THREE.Texture;
        const material = new THREE.MeshBasicMaterial({
            map: sky,
        });
        const mesh = new THREE.Mesh(geometry, material);
```
This is the output with expo 34 and expo-three 4.0.5+:
https://i.ibb.co/FmJ5kqj/image.png
This is how it was on expo 33 and expo-three 3.0.0+:
https://i.ibb.co/kQcLGKR/image.png

I tried expo-three 4.0.4 and I got this error when I load my obj models:
```
Can't find variable: THREE
<unknown>
    G:\project\node_modules\expo-three\node_modules\three\examples\js\loaders\OBJLoader.js:5:6
loadModuleImplementation
    G:\project\node_modules\metro\src\lib\polyfills\require.js:331:6
guardedLoadModule
    G:\project\node_modules\metro\src\lib\polyfills\require.js:197:45
loadObjAsync$
    G:\project\node_modules\expo-three\build\loaders\loadModelsAsync.js:48:15
...
```
If I dismiss the error, I can see the texture was loaded correctly before the error happened. So whatever happened in 4.0.5, it fixed obj model loading but ruined texture loading. I hope you can fix it soon.

NOTE: Thanks to https://github.com/expo/expo-three/issues/117#issuecomment-520124772 I could make it work with 4.0.4 at least, but of course I would prefer using the latest version.

**Comment by EvanBacon** [comment]
Really sorry about this, unfortunately the `global.THREE` issue is pretty unreliable because of the Metro bundler.
Could you please provide a repro?

**Comment by murat-mehmet** [comment]
Here you go: https://github.com/murat-mehmet/expo-three-texture-loader-error

**Comment by murat-mehmet** [comment]
Problem continues with v5.1.0.
