### ISSUE TITLE
problème de dépendance en react-native

### ISSUE THREAD

**Issue by siwar2019** [expo/expo-three#125]
am working on a project cloned from github i typed npm install soo a versionning problems appears  how can i update this dependencies  please , can  any one help me
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN expo-asset@1.1.1 requires a peer of expo-file-system@~1.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN expo-core@1.2.0 requires a peer of expo-react-native-adapter@~1.2.0 but none is installed. You must install peer dependencies yourself.
npm WARN expo-camera@1.1.1 requires a peer of react@^16.4.0 but none is installed. You must install peer dependencies yourself.
npm WARN expo-gl@1.0.2 requires a peer of react@^16.4.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-native-maps@0.21.0 requires a peer of react-native@^0.51 || ^0.52 || ^0.53 || ^0.54 but none is installed. You must install peer dependencies yourself.
npm WARN react-native-reanimated@1.0.0-alpha.6 requires a peer of react@16.0.0-alpha.6 but none is installed. You must install peer dependencies yourself.
npm WARN react-native-reanimated@1.0.0-alpha.6 requires a peer of react-native@^0.44.1 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-plugin-react-native@3.7.0 requires a peer of eslint@^3.17.0 || ^4 || ^5 but none is installed. You must install
peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

added 1091 packages from 568 contributors and audited 31300 packages in 375.964s
found 69 vulnerabilities (66 low, 3 high)

**Comment by EvanBacon** [comment]
Fixed in latest 5.5.1
