### ISSUE TITLE
Error Unable to resolve "three/examples/js/loaders/ctm/lzma" Expo sdk 34

### ISSUE THREAD

**Issue by jhonion** [expo/expo-three#126]
Hi,
I have been trying for a few days to install expo-three without success.
I get the following error when importing Expothree:

> _Unable to resolve "three/examples/js/loaders/ctm/lzma" from "node_modules\expo-three\build\loadClassForExtension.js"_

My package.json :
 _"dependencies": {
    "axios": "^0.19.0",
    "expo": "^34.0.4",
    "expo-linear-gradient": "^6.0.0",
    "expo-localization": "^6.0.0",
    "expo-three": "^5.0.0",
    "react": "^16.8.3",
    "react-native": "https://github.com/expo/react-native/archive/sdk-34.0.0.tar.gz",
    "react-native-confirmation-code-input": "^1.0.4",
    "react-native-gesture-handler": "^1.3.0",
    "react-native-reanimated": "^1.1.0",
    "react-native-svg": "^9.5.3",
    "react-navigation": "^4.0.0",
    "react-navigation-drawer": "^2.1.0",
    "react-navigation-stack": "^1.5.1",
    "react-navigation-tabs": "^2.4.0",
    "react-redux": "^5.0.0",
    "redux": "^4.0.1",
    "three": "^0.108.0"
  },
  "devDependencies": {
    "babel-preset-expo": "^5.0.0",
    "react-devtools": "^3.6.1",
    "schedule": "^0.5.0"
  },_

If someone is able to suggest an idea or solution, thank you

**Comment by pweisensee** [comment]
I also had this issue. I resolved it by reverting back to expo-three@4.x

Looks like a new issue introduced in a recent commit for v5

**Comment by Saikyun** [comment]
Had a similar issue: `Module not found: Can't resolve 'three/examples/js/loaders/ctm/CTMLoader' in '/Users/jona/spel/test-three/node_modules/expo-three/build'`

**Comment by jmatsushita** [comment]
Same error here.

**Comment by troyamtec** [comment]
Just remove 
        ```
case 'ctm':
            // @ts-ignore
            if (!THREE.CTMLoader) {
                require('../../three/examples/js/loaders/ctm/lzma');
                require('../../three/examples/js/loaders/ctm/ctm');
                require('../../three/examples/js/loaders/ctm/CTMLoader');
            }
            // @ts-ignore
            return THREE.CTMLoader;
```
from **expo-three/build/loaderClassForExtension.js**

**Comment by jhonion** [comment]
> I also had this issue. I resolved it by reverting back to [expo-three@4.x](mailto:expo-three@4.x)
> 
> Looks like a new issue introduced in a recent commit for v5

Thanks a lot, this solved my issue !

**Comment by EvanBacon** [comment]
Fixed in latest
