### ISSUE TITLE
Jpeg textures not loading on iOS

### ISSUE THREAD

**Issue by raphaelrk** [expo/expo-three#138]
[Snack link](https://snack.expo.io/@raphaelrk/three)

The above example show's Ben Affleck's face on web but on iOS it looks like a halftone moire pattern. Did not test on android. PNGs seem to work fine.

![IMG_2622](https://user-images.githubusercontent.com/3377845/66031858-3a117b00-e4d2-11e9-8ec5-9c64316fdc72.PNG)

**Comment by fenghengzhi** [comment]
i met the same problem on android too

**Comment by raphaelrk** [comment]
I've been using ImageManipulator to convert JPEG to PNG
https://docs.expo.io/versions/latest/sdk/imagemanipulator/

**Comment by raienko** [comment]
@fenghengzhi just convert your image assets to the `.png` format ( any online converter or photoshop ).

**Comment by fenghengzhi** [comment]
> @fenghengzhi just convert your image assets to the `.png` format ( any online converter or photoshop ).

i just do it in this way, it seems to be the only solution

**Comment by gavrix** [comment]
might be an issue with texture format. I've seen similar when loading texture from jpg file and manually changing format to RGBA fixed it. It's here https://github.com/expo/expo-three/blob/ef9732338c16b76cd4c3511e036ad7fbb7173884/src/TextureLoader.ts#L10
