### ISSUE TITLE
AWDLoader - Unable to resolve

### ISSUE THREAD

**Issue by uakhundz** [expo/expo-three#139]
Keep getting this error on a brand new project:

Unable to resolve "three/examples/js/loaders/AWDLoader" from "node_modules/expo-three/build/loaderClassForExtension.js"

Using 
    "expo": "^35.0.0",
    "expo-three": "^5.1.0",
    "react": "16.8.3",
    "react-native": "https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz"

**Comment by simongaviria1** [comment]
Having the same issue. Looks like the this file is missing from the node modules?

**Comment by Josh-McFarlin** [comment]
Just stumbled across this error. Looks like several loaders have been removed from three.js. Set the three package version in package.json to 0.88.0

**Comment by ebobo** [comment]
Got the same problem, I have set the three package version to 1.108.0 .  "three": "^0.108.0" and fixed it .

**Comment by tatsunori-iwaki** [comment]
I was the same.

"three": "^0.109.0",
I think it is because `three/examples/js/loaders/AWDLoader` is not found
https://github.com/expo/expo-three/blob/master/src/loaderClassForExtension.ts#L42
```
    case 'awd':
      // @ts-ignore
      if (!THREE.AWDLoader) {
        require('three/examples/js/loaders/AWDLoader');
      }
      // @ts-ignore
      return THREE.AWDLoader;
```

**Comment by jbrennan094** [comment]
@ebobo Thanks this solved it for me! Except it only worked after deleting/reinstalling node modules with npm. Didn't work with yarn or expo install for me.
