### ISSUE TITLE
ExpoTHREE.loadAsync(url) w/ querystrings/hashes cause "Unrecognized File Type"

### ISSUE THREAD

**Issue by burin** [expo/expo-three#14]
I wasn't sure if this was intentional, but this issue gets me a lot when I'm prototyping w/ random images off the internet :)

If I use a URL that includes anything after the file extension, I get the "Unrecognized File Type"  red screen. It's pretty easy to reproduce. 

It's not a huge issue, since there's a workaround (strip the stuff after the file extension).

```
// fails with query string (cache busters, etc)
const url = 'http://2.bp.blogspot.com/-NpG5ASzb7Uo/URjmnl0PTGI/AAAAAAAAEOs/UbGARn9OTsE/s1600/heart_pixelart_grid.png?haha=haha';

// fails with hash
const url = 'http://2.bp.blogspot.com/-NpG5ASzb7Uo/URjmnl0PTGI/AAAAAAAAEOs/UbGARn9OTsE/s1600/heart_pixelart_grid.png#hashie';

// works
const url = 'http://2.bp.blogspot.com/-NpG5ASzb7Uo/URjmnl0PTGI/AAAAAAAAEOs/UbGARn9OTsE/s1600/heart_pixelart_grid.png';

const spriteTexture = await ExpoTHREE.loadAsync(url);
```

**Comment by ericmorgan1** [comment]
Please double-check, but at least the query string issue should have been solved by pull #12.
[https://github.com/expo/expo-three/commit/f6d1bd902b21845855fa0fa5a738bd4571a733ae](url)

The hash would still be an issue though.

**Comment by EvanBacon** [comment]
As @ericmorgan1  said, the "query string" and the last one have been solved. I just pushed 2.2.0 which fixes the hashes!

**Comment by burin** [comment]
Awesome!
