### ISSUE TITLE
OrbitControls/MapControls not working

### ISSUE THREAD

**Issue by 5ervant** [expo/expo-three#147]
I have `"expo-three": "^5.2.0"` and `"three": "^0.110.0"`, and planning to use `MapControls` and to support both web and Android devices.

When I implement and test `OrbitControls` with the following code, I'm getting such error *"the 2nd parameter is now mandatory"* on an Android emulator:

    import { THREE } from 'expo-three';
    // global.THREE = global.THREE || THREE;
    import 'three/examples/js/controls/OrbitControls';
    
    let controls;
    //...
          onCreate={props => {
            //...
            controls = new THREE.OrbitControls(camera);
          }
          onUpdate={() => {
            controls.update();
            //...
          }}

Even though I implement `OrbitControls` as the following, it's still not working on both platforms and seems no effect without any warning:

    controls = new OrbitControls( camera, renderer.domElement );

Is there any updated guide to use camera controls such as OrbitControls or MapControls on both web and Android platforms? **Thanks!**

**Comment by Afrenchrussian** [comment]
+1 bump

**Comment by fredriklugg** [comment]
anyone gotten anywhere on this?

**Comment by Afrenchrussian** [comment]
I have ended up making a normal static webpage hosting it in gitpages and using web view to see it in expo

**Comment by jackynguyen93** [comment]
Looking for control solution

**Comment by banjianpan** [comment]
Did anyone figure out how to make orbit control work natively?

**Comment by banjianpan** [comment]
+1 bump

**Comment by banjianpan** [comment]
+1 bump

**Comment by banjianpan** [comment]
+1 bump

**Comment by EvanBacon** [comment]
`OrbitControls` will not work in a native React runtime because it relies heavily on DOM APIs. I just updated my experimental port of `OrbitControls` that uses `PanResponder` internally to pass delegate touch events [`expo-three-orbit-controls`](https://github.com/EvanBacon/expo-three-orbit-controls) -- I don't actively maintain `expo-three-orbit-controls` so you may need to fork it if you want to use a more stable touch system like `react-native-gesture-handler`.

**Comment by banjianpan** [comment]
What would be the best way to implement orbit controls? I'm just having a hard time understanding how your expo-three-orbit-controls works

**Comment by banjianpan** [comment]
I have been looking into react-three-fiber and saw this post on twitter(https://twitter.com/jmwind/status/1255101384338391040) but i dont really know how to implement react-three-fiber's orbit controls like shown on the twitter post

**Comment by 5ervant** [comment]
@banjianpan Then learn it. https://github.com/react-spring/react-three-fiber
A working sample _(not open-source yet)_ of their orbit control on the Techintel Item Displays' section: https://techintel.github.io/

**Comment by banjianpan** [comment]
The problem is i followed the implementation of react-three-fiber, but it doesnt work natively on my android emulator

**Comment by banjianpan** [comment]
Also @5ervant not everyone is as smart as you and can just "learn it". Why do you think I asked the question? Don't you think if i could just "learn it" I would have done so already and not post the question? Also I only post questions when i've already looked into the issue for a while. So just keep in mind that not everyone is as smart as you and can just "learn it". If you can't offer help then don't pretend like you can.

**Comment by 5ervant** [comment]
@banjianpan I guess it will not work on an android emulator perfectly, the best choice would be is to create a web version then just embed it by some sort of a RN/Expo function.

**Comment by itsezc** [comment]
For anyone still having this issue checkout: https://github.com/EvanBacon/expo-three-orbit-controls
