### ISSUE TITLE
suppressExpoWarnings not working

### ISSUE THREAD

**Issue by JulianKingman** [expo/expo-three#15]
I can't get expo to properly suppress the warnings. I put this at the top of my root file:
```javascript
import { THREE } from 'expo-three';
THREE.suppressExpoWarnings(true);
```
...but I still get tons of webgl warnings. Am I doing something wrong here? Using Android.
<img width="512" alt="screen shot 2018-01-10 at 2 31 27 pm" src="https://user-images.githubusercontent.com/1566400/34791438-fab47f66-f612-11e7-8a44-fc3af31c5406.png">

**Comment by SebastianMerz** [comment]
Having this issue as well.

**Comment by JulianKingman** [comment]
It's strange... looking into it further, it looks like the suppression script is running (by uncommenting this line: https://github.com/expo/expo-three/blob/95d58fd77884a89cf92108f27881534f0cc334bc/lib/suppressWarnings.js#L8), but it still logs the warning.

**Comment by EvanBacon** [comment]
@SebastianMerz  @JulianKingman You have to add `THREE.suppressExpoWarnings(true);` in [`componentWillMount`](https://github.com/expo/expo-three/blob/721cd26decf1338cbbc3f92556b10a8f98265217/examples/simple/App.js#L7-L12) for whatever reason...

**Comment by themakerman** [comment]
@EvanBacon the warnings is it something we should worry about? Gonna use this for making production APP.

**Comment by EvanBacon** [comment]
No the warnings are just parts of three.js that mean nothing in the context of EXGL.

**Comment by JulianKingman** [comment]
@EvanBacon thanks! It's probably some sort of race condition, so putting it in componentWillMount makes sure that it runs after global.console is already set up.

**Comment by michela98b** [comment]
Try this:

componentWillMount() {
    THREE.suppressExpoWarnings(true);
  }
