### ISSUE TITLE
Q: Handling touch events on React Native for 3D space

### ISSUE THREAD

**Issue by karloluis** [expo/expo-three#16]
I am using expo-three to create a 3D space and handling touches using a PanResponder. How would I approach converting the PanHandler x, y coordinates to identify where in my 3D model is it with respect to the set camera?

My assumption was this would be built in, but have not been able to find a suitable solution.

Thanks in advanced.

**Comment by EvanBacon** [comment]
@karloluis you can simply perform a raycast using three.js https://threejs.org/docs/#api/core/Raycaster

**Comment by karloluis** [comment]
Thank you, first time exploring the Threejs library and could not find a straight answer as I'm not familiar with 3D space methods.
