### ISSUE TITLE
Module not found: Can't resolve '@babel/runtime/helpers/classCallCheck'

### ISSUE THREAD

**Issue by cmv2** [expo/expo-three#160]
Running "npm install expo-three" and adding "import ExpoTHREE from 'expo-three';" to a working hello world Expo app results in failed compilation with "Module not found: Can't resolve '@babel/runtime/helpers/classCallCheck'  in '/home/user/node_modules/expo-three/build'"

**Comment by EvanBacon** [comment]
Should be fixed in the latest 5.5.1
