### ISSUE TITLE
loadCubeTextureAsync results in weird striped texture

### ISSUE THREAD

**Issue by marikka** [expo/expo-three#162]
I'm trying to use `loadCubeTextureAsync` to load and create a `CubeTexture`, to use for my `scene.background`. The texture seems to load, but the result is a weird striped texture. This happens both on iOS and Android

Is `loadCubeTextureAsync` known to work? It's not documented in the readme.

Is there another (better) way to create/use `CubeTexture`s?
 
Here's a link to the breaking code: https://github.com/marikka/expo-three-cubemap/blob/master/App.tsx
![image_from_ios](https://user-images.githubusercontent.com/61680/76983451-d100b100-6913-11ea-92ce-b5987f8ec210.png)

**Comment by timnlupo** [comment]
Same here

**Comment by santiagofm** [comment]
@marikka @timnlupo Did you guys find a solution to this issue?

**Comment by santiagofm** [comment]
Well, found the solution on another issue!

https://github.com/expo/expo-three/issues/138#issuecomment-602343377
