### ISSUE TITLE
How to implement gesture control to it?

### ISSUE THREAD

**Issue by exmlcxjv** [expo/expo-three#167]
I want to rotate And enlarge the object loaded. What is the proper solution to implement this?

**Comment by T0mAl3x** [comment]
Any hope on this? I'm still searching to find a proper solution to solve this

**Comment by exmlcxjv** [comment]
> Any hope on this? I'm still searching to find a proper solution to solve this

no bro, an alternate solution will be use webview on react-native to load threejs webpage.  gesture works

**Comment by T0mAl3x** [comment]
Found this project which is quite interesting. It uses ExpoGraphics instead of GLView
https://github.com/cryslub/history-expo
