### ISSUE TITLE
Example for loading Blender-THREE exported .json file 

### ISSUE THREAD

**Issue by chryb** [expo/expo-three#17]
I need to use bones created in Blender to control my mesh in ExpoThree. Is there an example to load `.json` files and render them in the scene. 

I tried `await ExpoTHREE.parseAsync(require('../../Assets/models/hand.json'))` to load the mesh but getting a strange error: `Requiring unknown module "3324"... `.

**Comment by thurber** [comment]
I'm experimenting with this now as well. I haven't yet figured out how to load a json as an asset, but I can show you my method for loading the model from an imported json file. A caveat is that I must instruct babel to ignore json files, since the bundler will choke on large files.

`.babelrc`
```
...
"ignore": [
  "**/*.json"
]
...
```

`App.js`
```
import Expo from 'expo';
import React from 'react';
import { Dimensions, StyleSheet, Text, View } from 'react-native';

import ExpoTHREE, { THREE } from 'expo-three';
THREE.suppressExpoWarnings(true);

import model from './assets/models/model.json';

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
});

export default class App extends React.Component {

  render() {
    return (
      <Expo.GLView
        style={styles.container}
        onContextCreate={ this._onGLContextCreate }
      />
    );
  }

  _onGLContextCreate = gl => {

    const { drawingBufferWidth: width, drawingBufferHeight: height } = gl;
    const { scale } = Dimensions.get( 'window' );

    // load model and materials from json
    const loader = new THREE.JSONLoader();
    const { geometry, materials } = loader.parse( model );

    // carry on with the usual scene building and rendering
    ...

  }

}
```

**Comment by chryb** [comment]
That's it! Thank you very much. Maybe it would be good to add this example to the documentation.
