### ISSUE TITLE
Update to three 125?

### ISSUE THREAD

**Issue by jedahan** [expo/expo-three#178]
Right now there are some errors I am receiving due to the change to defaulting to webgl2 i think

**Comment by XHMM** [comment]
## Update to three 127

in three [r127](https://github.com/mrdoob/three.js/releases/tag/r127), AssimpLoader has been [removed](https://github.com/mrdoob/three.js/pull/21459)

**Comment by pehagg** [comment]
So we're essentially stuck with a three release from 10+ months ago? Right.
