### ISSUE TITLE
Q: Can I use texture from remote url?

### ISSUE THREAD

**Issue by softnodelabs** [expo/expo-three#18]
I'm looking at the examples but I could not find a way to load remote textures. Is it possible?

**Comment by ericmorgan1** [comment]
[https://github.com/expo/expo-three/issues/10](url)

**Comment by softnodelabs** [comment]
Thank you ericmorgan1. I Tried the solution mentioned there, but it is not working. I have Expo-three 2.1.1 installed. I got the following message on XDE log:

[Unhandled promise rejection: Error: unexpected url: file:///data/user/0/host.exp.exponent/cache/ExperienceData/%2540softnodelabs%252Fsuabreja/ben-affleck-9176967-2-402.jpg]

The snack mentioned on the issue 10 is also not working.

**Comment by EvanBacon** [comment]
This worked at one point 🤷‍♀️ not sure what happened for you. I just pushed 2.2.0 which should have full support. I'll update the snack as soon as snack will let me 😁
