### ISSUE TITLE
Unable to resolve module `react-native-console-time-polyfill`

### ISSUE THREAD

**Issue by Cronnay** [expo/expo-three#20]
Hello there.

I get an error when I'm trying to work with this package and it says that it is unable to resolve module `react-native-console-time-polyfill`. It also gave me some advice to remove node_modules, clear $TMPDIR etc. I've tried all of these, but none of them works.

I'm just following your example you provided in the readme for this repo. I do believe it is something wrong with the ExpoTHREE-package, as it gives me the error when I try to include it.

![simulator screen shot - iphone 6s - 2018-01-22 at 13 10 39](https://user-images.githubusercontent.com/14805941/35220181-adbed9ba-ff75-11e7-90cd-c46f5ad7ac93.png)

I couldn't find any issues thas has been resolved, so I apologise if this is unnecessary.

Thanks in advance!

**Comment by EvanBacon** [comment]
Your console will warn you about missing peer dependencies. The readme needs updating but essentially just ‘yarn add react-native-console-time-polyfill’

**Comment by Cronnay** [comment]
Alright, thank you for your help.

However, after that dep I had to download 2 more - xmldom-qsa and text-encoding. After installing them, it worked fine! thanks!
