### ISSUE TITLE
Q: Is it possible to capture the renderer buffer and save it to an image?

### ISSUE THREAD

**Issue by softnodelabs** [expo/expo-three#21]
Hi, it's me again.

If I was using three in a browser, I would call the method toDataUrl from canvas. Is there anything similar available in Expo-Three ?

I need to get the rendered buffer and save it to a high quality png.

Edit: I used Expo.takeSnapshotAsync from Expo on the view containing the Expo.GLView and it worked for iOS but on Android I get only a black png.

Thanks.

**Comment by EvanBacon** [comment]
Sorry this went unnoticed. I believe this is similar to this: https://github.com/expo/expo/issues/1371 there is great new feature coming soon that will give us the ability to save the current state of the buffer.
