### ISSUE TITLE
ExpoTHREE.getPlanes not detecting any planes

### ISSUE THREAD

**Issue by erikparr** [expo/expo-three#22]
Hi I can't actually detect any planes with getPlanes function. I can get feature points using getRawFeaturePoints but when I try to detect planes planes.length always seems to return 0.  I'm developing with the latest expo and expo-three. I am new to expo and react - any help is much appreciated thanks.

`    const { planes } = ExpoTHREE.getPlanes(this.arSession);
    if (planes.length > 0) {
      console.log("found plane");
    }
`

planes.length is always 0

**Comment by erikparr** [comment]
I'm familiar with ARKit in Unity and have scanned around long enough for ARKit to return something. Is this feature functional only in the developmental "unversioned" github version or on the stable 25.0.0 version? (Btw if there were a working example for plane detection in the future it would be very much appreciated.) 

I'll attach my code in case I am missing something obvious. Thank you for the help

`import ExpoGraphics from 'expo-graphics';
import ExpoTHREE, { THREE } from 'expo-three';
import React from 'react';
import { PanResponder, PixelRatio, View } from 'react-native';

export default class App extends React.Component {
  boxGeometry = new THREE.BoxGeometry(0.04, 0.04, 0.04);

  componentWillMount() {
    THREE.suppressExpoWarnings(true);

    const panGrant = (_, gestureState) => {
      const { featurePoints } = ExpoTHREE.getRawFeaturePoints(this.arSession);
      if (featurePoints.length > 0) {
        featurePoints.map(position => this.addBox(position));
      }
    };
    const panRelease = (_, gestureState) => {};
    this.panResponder = PanResponder.create({
      onStartShouldSetPanResponder: () => true,
      onPanResponderGrant: panGrant,
      onPanResponderRelease: panRelease,
      onPanResponderTerminate: panRelease,
      onShouldBlockNativeResponder: () => false,
    });
  }
  render() {
    return (
      <View {...this.panResponder.panHandlers} style={{ flex: 1 }}>
        <ExpoGraphics.View
          pointerEvents="none"
          style={{ flex: 1 }}
          onContextCreate={this.onContextCreate}
          onRender={this.onRender}
          onResize={this.onResize}
          arEnabled
        />
      </View>
    );
  }

  onContextCreate = async (gl, arSession) => {
    this.material = new THREE.MeshBasicMaterial({
      map: await ExpoTHREE.loadAsync(require('./assets/icons/app-icon.png')),
    });

    this.arSession = arSession;
    const { drawingBufferWidth, drawingBufferHeight } = gl;
    const scale = PixelRatio.get();

    const width = drawingBufferWidth / scale;
    const height = drawingBufferHeight / scale;

    // renderer
    this.renderer = ExpoTHREE.createRenderer({
      gl,
    });
    this.renderer.setPixelRatio(scale);
    this.renderer.setSize(width, height);
    this.renderer.setClearColor(0x000000, 1.0);

    /// Standard Camera
    this.camera = new THREE.PerspectiveCamera(50, width / height, 0.1, 10000);
    this.camera.position.set(5, 5, -5);
    this.camera.lookAt(0, 0, 0);

    this.scene = new THREE.Scene();
    this.scene.add(new THREE.GridHelper(5, 6, 0xffffff, 0x555555));

    this.setupLights();

    // AR Background Texture
    this.scene.background = ExpoTHREE.createARBackgroundTexture(arSession, this.renderer);


    /// AR Camera
    this.camera = ExpoTHREE.createARCamera(arSession, width, height, 0.01, 1000);

    /// Enable ARKit light estimation
    ExpoTHREE.setIsLightEstimationEnabled(arSession, true);

    /// Enable ARKit plane detection - this will let us get the raw point data
    ExpoTHREE.setIsPlaneDetectionEnabled(arSession, true);


    const { planes } = ExpoTHREE.getPlanes(this.arSession);
    if (planes.length > 0) {
      console.log("found plane");
    }

    // planes.forEach(
    //   ({ center: { x, y, z }, extent: { width, height }, transform, id }) => {}
    // );

    // planes.forEach(
    //   ({ center: { x, y, z }, extent: { width, height }, transform, id }) => {
    //     // grid
    //     var size = this.width*this.height, step = size/20;
    //     var geometry = new THREE.Geometry();
    //     for( var x = 0; x < extent.width; x+=step){
    //       for( var z = 0; z < extent.height; z+=step){
    //         geometry.vertices.push(new THREE.Vector3(x, 0, z));
    //       }
    //     }
    //     var material = new THREE.LineBasicMaterial({ color: 0x000000, opacity: 0.2, transparent: true });
    //     var line = new THREE.LineSegments(geometry, material);
    //     this.scene.add(line);
    //
    //   },
    // );

  };

  setupLights = () => {
    this.light = new THREE.DirectionalLight(0x002288);
    this.light.position.set(-1, -1, -1);
    this.scene.add(this.light);

    const light = new THREE.AmbientLight(0x222222);
    this.scene.add(light);
  };

  addBox = async ({ x, y, z, id }) => {
    const cube = new THREE.Mesh(this.boxGeometry, this.material);
    // console.warn(point);
    cube.position.set(x, y, z);
    this.scene.add(cube);
  };

  addPlane = async ({ center: { x, y, z }, extent: { width, height }, transform, id  }) => {
    const cube = new THREE.Mesh(this.boxGeometry, this.material);
    // console.warn(point);
    cube.position.set(x, y, z);
    this.scene.add(cube);
  };

  onResize = ({ width, height }) => {
    const scale = PixelRatio.get();
    this.camera.aspect = width / height;
    this.camera.updateProjectionMatrix();
    this.renderer.setPixelRatio(scale);
    this.renderer.setSize(width, height);
  };

  onRender = () => {
    const lightEstimation = ExpoTHREE.getARLightEstimation(this.arSession);
    if (lightEstimation) {
      this.light.intensity = 1 / 2000 * lightEstimation.ambientIntensity;
      // this.light.ambientIntensity = lightEstimation.ambientColorTemperature;
    }

    const { scene, renderer, camera } = this;
    renderer.render(scene, camera);
  };
}
`

**Comment by erikparr** [comment]
I've managed to get it working which is great but now a few issues with the values that getPlanes is returning:
-The center y position is always returning 0 - but x and z always give the right value. Also height always returns as undefined but width returns the correct value. 

```
[exp] x: 0.6967779994010925 y: 0 z: 0.040124520659446716
[exp] width: 1.8006969690322876 height: undefined

```
I also dont see any way to currently get the plane orientation from ARKit - has this feature been implemented? It would be great to be able to work with defined planes.

Any help is much appreciated

**Comment by EvanBacon** [comment]
It's important to not that hit test isn't in Expo yet, it'll compute any position on the screen regardless of the raw data ( apple doesn't return enough data to compute this accurately ). 
Here is a full example of planes and points: https://snack.expo.io/@bacon/arkit-example
