### ISSUE TITLE
Invalid pixel data argument for gl.textImage2D()!

### ISSUE THREAD

**Issue by ericmorgan1** [expo/expo-three#23]
I am getting this error when loading remote images.

`"THREE.WebGLState:", "EXGL: Invalid pixel data argument for gl.textImage2D()!"`

Error can be dismissed, but the image appears as all black.

Snack:
https://snack.expo.io/By2XW0oUG

I believe similar code was working the last time I tried it.

**Comment by EvanBacon** [comment]
Not sure whats wrong but it's not the texture loading: https://snack.expo.io/@bacon/expo-graphics-ar-remote-image-example
