### ISSUE TITLE
Cannot load texture from URI from phone device

### ISSUE THREAD

**Issue by TeamBaconn** [expo/expo-three#236]
Hi, i'm using expo three in my react-native project. I can not load texture from URI using expo three TextureLoader and apply it onto my object. This method only work on web, not my iphone. Here is my snack: https://snack.expo.dev/@baconn00/three
This is on the snack
![image](https://user-images.githubusercontent.com/21982808/140636876-027c173c-909b-4976-aa83-a462fd04c811.png)
This is what my phone looks like
![image](https://user-images.githubusercontent.com/21982808/140636861-a471ce30-0fdf-4c17-a664-51ecf7e5b9c2.png)
I would be appreciated for any help, thankyou

**Comment by romerorickyio** [comment]
I'm having the same issue. I am using the same expo-three example code. 
I get this warning message

```
 "[Unhandled promise rejection: TypeError: undefined is not an object (evaluating '_$$_REQUIRE(_dependencyMap[7], "expo-modules-core").Platform.OS')]" 

Stack trace:
node_modules/expo-asset/build/AssetSources.js:38:112 in selectAssetSource
node_modules/expo-asset/build/Asset.js:92:30 in fromMetadata
node_modules/expo-asset/build/Asset.js:83:15 in fromModule
...
```

**Comment by danmaas** [comment]
I bisected versions of `three` and found that `TextureLoader.load(url)` works fine with `three` <= 0.135 and does not work with `three` >= 0.136.

Between 0.135 and 0.16, there are changes to how GL textures are uploaded in `src/renderers/webgl/WebGLTextures.js`. I suspect these changes made `three`'s texture uploads no longer work with latest versions of the Expo SDK.

My working versions:
```
    "expo": "^45.0.0",
    "expo-gl": "~11.3.0",
    "expo-gl-cpp": "~11.3.0",
    "expo-three": "~6.0.1",
    "three": "^0.135.0",
```

Here is an Expo Snack that reproduces the issue on Expo SDK 45: https://snack.expo.dev/@maas38288/web-texture-issue
If you open the app on Android, then go into package.json and change the version of "three" from 0.135.0 to 0.136.0, the texture disappears and the cube renders as black.
