### ISSUE TITLE
Question: How to make object position relative to device

### ISSUE THREAD

**Issue by ericmorgan1** [expo/expo-three#24]
I made a Snack here: https://snack.expo.io/ryABMCsLf

When you press the Add button, it should position an image at (0, 0, -0.7) [Slightly in front of the camera].
However, if I walk somewhere, or rotate the device, and press Add again, it adds the image back in the original position.

It seems that the device's position gets initialized once and never updated, even if the device moves.
How can I refresh that position so that adding new images will be relative to the camera's current position?

**Comment by ykn121** [comment]
did you solve the problem?

**Comment by ericmorgan1** [comment]
@ykn121 I believe you need to set the position of the `geometry` rather than the mesh. Not sure it that is the correct method, though.

**Comment by EvanBacon** [comment]
The camera moves around in ARKit but the world doesn't, you can use trig to calculate a position in front of a camera given the cameras rotation and position (matrix). I think three.js has a convenience function that can calculate this for you though.

**Comment by EvanBacon** [comment]
fixed in the next Expo SDK (28)
