### ISSUE TITLE
Cannot use TextureLoader Expo SDK 45.

### ISSUE THREAD

**Issue by TeamBaconn** [expo/expo-three#263]
Its show Value is undefined, expected an Object no stack when ever i use new TextureLoader().load(url). I'm using SDK 45
    "expo": "~45.0.0",
    "expo-three": "^5.7.0",
    "expo-gl": "~11.3.0",
Can someone help me with this error? I tried everything i got

**Comment by danmaas** [comment]
I'm not 100% sure, but I suspect Expo SDK removes the ability to load a texture directly from a non-local URI on native platforms. (would love confirmation on this!)

I am trying a work-around that downloads the image using `FileSystem.downloadAsync()` and passes the resulting local URI.

**Comment by danmaas** [comment]
Update: the above is mistaken. It's not an expo change. I bisected versions of `three` and found that `TextureLoader.load(url)` works fine with `three` <= 0.135 and does not work with `three` >= 0.136.

Between 0.135 and 0.16, there are changes to how GL textures are uploaded in `src/renderers/webgl/WebGLTextures.js`. I suspect these changes made `three`'s texture uploads no longer work with latest versions of the Expo SDK.

My working versions:
```
    "expo": "^45.0.0",
    "expo-gl": "~11.3.0",
    "expo-gl-cpp": "~11.3.0",
    "expo-three": "~6.0.1",
    "three": "^0.135.0",
```

**Comment by danmaas** [comment]
I believe this might be the result of some version skew among the Expo and Three packages. Below are the list of known-good packages I am using:

```
  "dependencies": {
    "expo": "^45.0.0",
    "expo-gl": "~11.3.0",
    "expo-gl-cpp": "~11.3.0",
    "expo-three": "~6.0.1",
    "three": "^0.135.0",
   },
  "resolutions": {
    "**/@expo/browser-polyfill": "^1.0.0",
   }
```
