### ISSUE TITLE
How to implement drag & drop of a model?

### ISSUE THREAD

**Issue by greg-js** [expo/expo-three#27]
Hi, thanks for your hard work, loving the project!

Raycasting and handling taps is straightforward, but could you maybe point me in the right direction as to how to implement a drag & drop? I can't seem to figure out how to "pick up" a model and drag it with my finger. Linking up `PanResponder` with `Three.js` isn't exactly obvious and I can't use `Animated.View` so the stuff I find online isn't very relevant. Thanks again for this project!

**Comment by EvanBacon** [comment]
The three.js stuff is mostly just raw three.js/javascript without react. Here is an example of a hit test: https://snack.expo.io/@bacon/arkit-example
Here is another one in an experimental engine thing I'm working on: https://github.com/expo/exotic/blob/c8836f38c971dd4e4b12d385be6c33d9e8bde457/examples/simple/Game/levels/PlayingLevel.js#L83-L98

**Comment by abdielou** [comment]
@greg-js Yes, you can use `Animated.View`. I have an `Animated.View` wrapping an `ExpoGraphics.View`. The `PanResponder` captures the touch event positions. What I do is to set those positions in the react `state` and then update the 3D objects at `ExpoGraphics.View#onRender`.

**Comment by greg-js** [comment]
Thank you both for the pointers! I'm sure I'll figure it out!

**Comment by fixed-term-tylernguyen** [comment]
Hello, 
were you able to figure this implementation out?
