### ISSUE TITLE
Rendering OBJ/MTL breaks when texture image is NPOT

### ISSUE THREAD

**Issue by abdielou** [expo/expo-three#28]
Here's the code: https://github.com/abdielou/npot-bug-demo

When rendering models with NPOT texture images, the app breaks with the following stack trace:

```
Can't find variable: HTMLImageElement
makePowerOfTwo
uploadTexture three.js:18101:25
setTexture2D
setTexture2D
setValueT1 three.js:4971:2
...
```

Version:
```
  "dependencies": {
    "expo": "^25.0.0",
    "expo-graphics": "^0.0.3",
    "expo-three": "^2.2.2-alpha.1",
    "react": "16.2.0",
    "react-native": "0.52.0",
    "three": "^0.90.0"
  }
```
![screenshot_20180226-170502](https://user-images.githubusercontent.com/1036734/36696357-5608bc8e-1b1a-11e8-810e-031a63682044.png)

**Comment by EvanBacon** [comment]
I think this might be an android bug, will test and get back to you.

**Comment by abdielou** [comment]
@EvanBacon Just tried it out on iOS. Same thing.

**Comment by EvanBacon** [comment]
Canvas isn't supported in React Native, we have someone actively working on it. Basically this is taking an image and making it power of two using canvas. As for the actual error, I wrote a lib called @expo/browser-polyfill which should fix it, I'll try to implement it soon <3

**Comment by abdielou** [comment]
I tried using your polyfill but from what I recall it was missing `ImageBitmap`.

**Comment by EvanBacon** [comment]
I fixed this in `@expo/browser-polyfill` should work for you now
