### ISSUE TITLE
Please update to expo 47

### ISSUE THREAD

**Issue by obasille** [expo/expo-three#287]
Hi there, thank you for this very useful package :)
Would it be possible to update to expo 47 / React Native 0.70?

I'm getting this dependency warnings:
"expo-three#@expo/browser-polyfill##expo-file-system@^13.2.0" doesn't satisfy found match of "expo-file-system@15.1.1"
"expo-three#@expo/browser-polyfill##react@^17.0.1" doesn't satisfy found match of "react@18.1.0"
"expo-three#@expo/browser-polyfill##react-native@^0.64.3" doesn't satisfy found match of "react-native@0.70.5"

Thanks a lot!

**Comment by tiomun** [comment]
I recently had to update our application to Expo 47 and have the same issue. In addition to the dependency errors expo-three fails to run.

**Comment by MartynFitzgerald** [comment]
Did anyone find a solution to these errors or do we need to wait for them to update expo-three?

**Comment by obasille** [comment]
@tiomun the dependency messages I've reported are warnings, not errors, they are probably unrelated to your issue.
I'm currently running without issue on Android with these pacakages (I haven't tested on iOS):
```
    "expo": "~48.0.10",
    "expo-file-system": "~15.2.2",
    "expo-three": "^7.0.0",
    "react": "18.2.0",
    "react-native": "0.71.6",
    "three": "^0.145.0"
```

**Comment by markrickert** [comment]
Can you see if this is still an issue with `"expo-three": "^8.0.0",`?

**Comment by obasille** [comment]
Thank you for the update @markrickert!
I still get those warnings (which I'm realizing come from browser-polyfill 1.0.1 imported by expo-three) but most importantly it's wonderful news that we can now use a recent version of Three.js with Expo!!
Also it got rid a runtime "scary" warnings I was getting: " EXGL: gl.pixelStorei() doesn't support this parameter yet!"

**Comment by markrickert** [comment]
@obasille look in the examples and you'll find the code to mitigate the `pixelStorei` issue! https://github.com/expo/expo-three/blob/master/example/app/spinning-cubes.tsx#L35-L43
