### ISSUE TITLE
Ignore `gl.pixelStorei` warning

### ISSUE THREAD

**Issue by Josema** [expo/expo-three#293]
I am getting this error every time I load a texture. 
` LOG  ABI48_0_0EXGL: gl.pixelStorei() doesn't support this parameter yet!`

I load hundred of textures, is there any way to ignore or solve this issue? It makes my console.log unusable.

**Comment by kevinhu** [comment]
[This fix](https://github.com/expo/expo-three/issues/196#issuecomment-1334807693) worked for me:
```tsx
<Canvas
onCreated={(state) => {
  const _gl = state.gl.getContext();
  const pixelStorei = _gl.pixelStorei.bind(_gl);
  _gl.pixelStorei = function (...args) {
    const [parameter] = args;
    switch (parameter) {
      case _gl.UNPACK_FLIP_Y_WEBGL:
        return pixelStorei(...args);
    }
  };
}}
/>
```

**Comment by Josema** [comment]
It works, thank you.

**Comment by didemkkaslan** [comment]
worked for me too!

thansk
