### ISSUE TITLE
How to upgrade expo-three to use the latest version of three.js

### ISSUE THREAD

**Issue by Josema** [expo/expo-three#298]
Is it possible to upgrade this module to use the latest version of three.js?

**Comment by markrickert** [comment]
@Josema I'm working on this! Check out my branch here and let me know if it works for you! You can try it in your project by making the package.json entry: `"expo-three": "markrickert/expo-three#dev"`

**Comment by Sai-Smaran** [comment]
@markrickert I am getting an import error: 
`Unable to resolve "expo-three" from "App.js"`

**Comment by Josema** [comment]
I am getting the same error than @Sai-Smaran. Can you help here @markrickert ?

`Unable to resolve "expo-three" from "node_modules/conkis-three/index.js"`

**Comment by markrickert** [comment]
Version 8.0.0 has landed with `0.166.0` support!
