### ISSUE TITLE
Question : Is it possible to use complex materials ?

### ISSUE THREAD

**Issue by gaschavardes** [expo/expo-three#30]
Hi !
I just got to use expo-three and I was wondering if we could use materials like : 

const material = new THREE.MeshBasicMaterial( { color: 0xffffff, envMap: this.scene.background } );

It would make sense in three I guess but here all I got is a black texture
Thanks !

**Comment by AndresCuervo** [comment]
What do you mean by complex materials? Physically based lighting & `ShaderMaterial` all works just as expected in expo-three.

 Presumably you were trying to pass an `envMap` in to get some projection working, right?  A material's `envMap` should be a loaded texture reflecting the projection you're trying to achieve. For a cube map that would be a [CubeTextureLoader](https://threejs.org/docs/#api/loaders/CubeTextureLoader). See [this example](https://threejs.org/examples/webgl_materials_envmaps.html) for more exploration of env. maps in Three.

**Comment by gaschavardes** [comment]
Ok thanks !
I kind of achieve what I wanted to do but thanks for the information !
