### ISSUE TITLE
Forward facing camera?

### ISSUE THREAD

**Issue by AndresCuervo** [expo/expo-three#31]
This project is amazing, really been enjoying using Three.js with ARKit! I saw some references to geometry `faces` but didn't see anything about access the front-facing camera & by extension [ARFaceGeometry](https://developer.apple.com/documentation/arkit/arfacegeometry). Would be really cool to manipulate face meshes using Three! Any plans to support this or did I miss something? Thanks!

**Comment by EvanBacon** [comment]
This is planned and will hopefully be released in the next 2-3 releases

**Comment by AndresCuervo** [comment]
Great news to hear that this is planned, thanks for the update @EvanBacon!

**Comment by EvanBacon** [comment]
Should be coming out soonish (based on apple approving the new build)

**Comment by EvanBacon** [comment]
SDK 28 / expo-three 3.0.0-alpha.1 has support
