### ISSUE TITLE
Creating IPA project AR fails

### ISSUE THREAD

**Issue by aldooktana** [expo/expo-three#32]
Hi,
I'm having a weird issue, I wrote my own app in expo and one of those views uses expo three with AR.
I was testing with the expo app and expo three with AR works great but when trying to export my project with exp build:ios everything works but when it comes to the AR I'am not able to see the camera and the app freeze.
I tried with the example AR code that is in this snack: https://snack.expo.io/Hk1C_YqjW and i have the same problem. I also granted the camera permission.
I don't believe there is a problem with the dependencies because creating ExpoTHREE.createARCamera without arSession works great.
Thanks.

**Comment by EvanBacon** [comment]
hmm, sorry this has slipped my radar. Were you able to figure out your problem?

**Comment by EvanBacon** [comment]
We should check this again with AR in SDK28, I just rewrote all of it and it should be dropping soon

**Comment by EvanBacon** [comment]
I was able to build the `expo-three/example` and deploy to the app store. Closing
