### ISSUE TITLE
ARCore support 

### ISSUE THREAD

**Issue by robertjuh** [expo/expo-three#36]
Hi,

was trying to test out the augmented reality portion but i only have an Android device. Given that ARCore was recently releasing a new version, will you also make it compatible with ARCore?

**Comment by EvanBacon** [comment]
I don't really have the bandwidth at the moment to integrate this feature. The native code will need to be added to this repo https://github.com/expo/expo if you would like to open a PR that will probably be the fastest way right now

**Comment by robertjuh** [comment]
Alright, then i'll probably have to close this issue.

**Comment by Arevy** [comment]
Some news about ARCore? I really need this compatibility soon ... :( 
Will the technology be compatible with the web?
