### ISSUE TITLE
Render at lower resolution

### ISSUE THREAD

**Issue by elxris** [expo/expo-three#39]
Is this possible, I've tried the things that works on Web with no success.

The first thing is to change the pixel ratio while conserving the same size (like in [this web example)](https://jsfiddle.net/x4p3bcua/74/)
```
this.renderer.setPixelRatio(scale * 0.5);
this.renderer.setSize(width, height);
```
Try [snack](https://snack.expo.io/ByFuFpU6f)

And this gave me a half screen sized render, not lower resolution full screen render.

The second thing I tried is the [threejs documentation way](https://threejs.org/docs/#manual/introduction/Creating-a-scene) which is 

> If you wish to keep the size of your app but render it at a lower resolution, you can do so by calling setSize with false as updateStyle (the third argument). For example, setSize(window.innerWidth/2, window.innerHeight/2, false) will render your app at half resolution, given that your <canvas> has 100% width and height.

Kinda translate to this [web example](https://jsfiddle.net/x4p3bcua/76/)

Which (kind of) translates to:
```
// this.renderer.setPixelRatio(scale);
    this.renderer.setSize(width, height);
    this.renderer.setSize(width * 0.5, height * 0.5, false);
```
Try [snack](https://snack.expo.io/SJkBGR8Tf)

And the same result as above.

So, my first impression it's all about a small bug.

If there is a way to do this please provide me a expo snack.

Lastly but equally important: This is an awesome tool, thanks for your support.

**Comment by EvanBacon** [comment]
Hmm, yeah that CSS trick doesn't work AFAIK. You can get pretty similar perf by using a composer then rendering to a blank shader and downsampling the effect.
https://snack.expo.io/@bacon/three-low-res
