### ISSUE TITLE
Plane detection?

### ISSUE THREAD

**Issue by tvararu** [expo/expo-three#4]
Great work on this. 👏 

I see you [mentioned plane detection on this issue](https://github.com/expo/expo/issues/638), but has anything been done in this direction?

Currently considering trying to extract some features from [react-native-arkit](https://github.com/HippoAR/react-native-arkit) which apparently does have plane detection of some sort.

**Comment by pierotofy** [comment]
Proposed changes for plane detection: https://github.com/expo/expo-three/pull/13

**Comment by EvanBacon** [comment]
Merged! Works in expo 25.0.0 and expo-three 2.2.0
