### ISSUE TITLE
3ds file not loading

### ISSUE THREAD

**Issue by ambewas** [expo/expo-three#41]
Getting an error -> "ExpoTHREE.loadAsync: OMG this asset couldn't be downloaded! Open an issue on GitHub"

App.json ->
```
{
  "expo": {
    "sdkVersion": "27.0.0",
    "packagerOpts": {
      "assetExts": [
        "dae",
        "obj",
        "amf",
        "mtl",
        "3DS"
      ]
    }
  }
}
```

uncapitalised, I'm getting an unexpected character error

**Comment by ambewas** [comment]
closing -- small mistake in the code.

**Comment by EvanBacon** [comment]
What was the error in code? I need to make a more helpful error message.

**Comment by ambewas** [comment]
my mistake. I tried to load in an mtl as well that I didn't specify :)

**Comment by EvanBacon** [comment]
Ok thanks, will try and be more clear. Sorry for the inconvenience 😅

**Comment by ambewas** [comment]
No prob! Thanks for the cool lib btw 😃
