### ISSUE TITLE
learning ExpoTHREE.getPlanes()

### ISSUE THREAD

**Issue by NippleTerminator** [expo/expo-three#42]
sorry I am having a hard time to learn how to use this method, can someone recommend where I can find examples to learn placing an object to a detected plane(such as a length measurer example)? 

I tried google many times but all the examples I find mainly involve three.js only, without any plane manipulation with objects

and I am sorry i hope I am not asking these questions in a wrong place I also tried to find [expo-three] on stackoverflow but with no luck

kevin

**Comment by EvanBacon** [comment]
No worries my main, get planes is very experimental. I just wrote one that will actually work as you expect, basically you get a "magnetic node" and you can use it to stick to planes. Hopefully it'll be out in v29 of expo. Then I'll be adding a TON of extra expo-three features that cover all ARKit features. But yes you are right the raw data is mostly useless atm 😅
