### ISSUE TITLE
Mtl cache & asset couldn't be downloaded

### ISSUE THREAD

**Issue by WeiMin1** [expo/expo-three#44]
Hi,

I'm totally new to react native and expo/expo-three.
I am trying to build a simple 3d scene, and now i'm just loading in some test obj.

I ran in to some issues 
Error: You tried to download an Expo.Asset and for some reason it didn't cache... Known reasons are: it's an .mtl file
and console.error"ExpoThree.loadAsync:OMG,this asset couldn't be downloaded! Open an issue on GitHub."

If i remove the mtl line from loading the mesh the obj loads fine, but without any textures. My app.json also includes mtl as well.

How do i load texture without the mtl? Is that possible?

https://snack.expo.io/@wmts/batman-obj
Here's the snack version of my js file.

**Comment by EvanBacon** [comment]
#40 #3d
