### ISSUE TITLE
Couldn't find preset "es2015" relative to directory "/<project>/node_modules/gl-matrix"

### ISSUE THREAD

**Issue by ericmorgan1** [expo/expo-three#47]
I recently upgraded to Expo v28.
When I `import { THREE } from 'expo-three';`, I get this error:

`Couldn't find preset "es2015" relative to directory "/<project>/node_modules/gl-matrix"`

I was able to fix it (I think) by running:
`npm install babel-cli babel-preset-es2015`

However, can this dependency be packaged with the `expo-three` install?

Here is my package.json:

```
{
  "main": "node_modules/expo/AppEntry.js",
  "private": true,
  "scripts": {
    "test": "node ./node_modules/jest/bin/jest.js --watchAll"
  },
  "jest": {
    "preset": "jest-expo"
  },
  "dependencies": {
    "@expo/samples": "2.1.1",
    "expo": "^28.0.0",
    "expo-graphics": "^1.0.0-alpha.1",
    "expo-three": "^3.0.0-alpha.1",
    "firebase": "^5.0.4",
    "react": "16.3.1",
    "react-native": "https://github.com/expo/react-native/archive/sdk-28.0.0.tar.gz",
    "react-navigation": "2.3.1"
  },
  "devDependencies": {
    "jest-expo": "^28.0.0"
  }
}
```

**Comment by EvanBacon** [comment]
Closing with e7455e1304895ae7204beb34ba5f92bbf5aaaf26 sorry for the inconvenience. Related: https://github.com/expo/expo-pixi/issues/17
