### ISSUE TITLE
can't find variable : loadAsync

### ISSUE THREAD

**Issue by AnisDerbel** [expo/expo-three#51]
I faced this problem so many times, it works at the beginning when I run the example that you provide and suddenly this appear and always appears even after restarting my laptop.

Didn't figure it out why it happens.everything is setup correctly, I used the last version from master branch.

**Comment by EvanBacon** [comment]
Could you please share a demo that reproduces this error. Also information regarding your test device, expo version, would be helpful

**Comment by EvanBacon** [comment]
Stale, closing.
