### ISSUE TITLE
Expo-Three Interferes with Firebase

### ISSUE THREAD

**Issue by ericmorgan1** [expo/expo-three#53]
Hello,

**Versions:**
Expo: 28
Expo-Three: 3.0.0-alpha.2
Firebase: 5.0.4

**Issue:**
Whenever I import anything from `expo-three`, some components of the Firebase SDK do not work properly. Specifically, querying the realtime database does not work. The callback functions do not get called, but no errors are logged.

`firebase.database().ref("test").on("value", fnSuccess, fnFailure);`

I've narrowed it down to `expo-three` and put a simple app here:
https://github.com/ericmorgan1/expo-three-firebase

In `App.js`, commenting/uncommenting the `expo-three` import will cause the firebase callbacks to either fire or not fire.

I know this issue is related to a third-party product, and I would be happy to do some debugging or other testing. But since there were no error messages, it was difficult figuring out where to begin.

I also tried this with Firebase SDK v4.10 and got the same issues.

**Comment by EvanBacon** [comment]
Looks like I broke it again: https://github.com/expo/browser-polyfill/issues/2
Related to one of the browser polyfills.

**Comment by EvanBacon** [comment]
Closing, the other issue should follow this more clearer
