### ISSUE TITLE
ThreeAR.Camera freezes after using Expo.Camera on another screen

### ISSUE THREAD

**Issue by briangainer** [expo/expo-three#55]
After I use the Expo.Camera or Expo.ImagePicker camera component in one of my app tabs, the ThreeAR.Camera in my Expo AR Scene in the other tab freezes.

Is there a way to reset the ThreeAR.Camera after using the phone's camera in another screen?

Thanks

**Comment by EvanBacon** [comment]
You can destroy the camera instance by calling: 
```js
Expo.AR.stopAsync();
```
