### ISSUE TITLE
Can't add the expo-three library to my project!

### ISSUE THREAD

**Issue by simonrajter** [expo/expo-three#58]
I was following this tutorial: https://blog.expo.io/introducing-expo-ar-mobile-augmented-reality-with-javascript-powered-by-arkit-b0d5a02ff23

And then when I had tu run this command: npm i -S three expo-three
I got a lot of errors.

Command line errors:
PS D:\Moji dokumenti\diplomska\app> npm i -S three expo-three

> @expo/browser-polyfill@0.0.0-alpha.10 postinstall D:\Moji dokumenti\diplomska\app\node_modules\@expo\browser-polyfill
> find ../ -name .babelrc -delete

FIND: Parameter format not correct
my-new-project@ D:\Moji dokumenti\diplomska\app
`-- three@0.95.0

npm WARN eslint-plugin-react-native@3.2.1 requires a peer of eslint@^3.17.0 || ^4.0.0 but none was installed.
npm WARN expo-asset-utils@0.0.4-alpha.3 requires a peer of expo@^25.0.0 but none was installed.
npm WARN react-native-maps@0.21.0 requires a peer of react-native@^0.51 || ^0.52 || ^0.53 || ^0.54 but none was installed.
npm WARN react-native-reanimated@1.0.0-alpha.3 requires a peer of react@16.0.0-alpha.6 but none was installed.
npm WARN react-native-reanimated@1.0.0-alpha.3 requires a peer of react-native@^0.44.1 but none was installed.
npm WARN expo-three@3.0.0-alpha.4 requires a peer of expo@^28.0.0 but none was installed.
npm WARN expo-three@3.0.0-alpha.4 requires a peer of three@0.88.0 but none was installed.
npm WARN @expo/browser-polyfill@0.0.0-alpha.10 requires a peer of expo@^28.0.0 but none was installed.
npm WARN @expo/browser-polyfill@0.0.0-alpha.10 requires a peer of react@16.3.0 but none was installed.
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @expo/browser-polyfill@0.0.0-alpha.10 postinstall: `find ../ -name .babelrc -delete`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the @expo/browser-polyfill@0.0.0-alpha.10 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

┌───────────────────────────────────────────────────────────┐
│                  npm update check failed                  │
│            Try running with sudo or get access            │
│           to the local update config store via            │
│ sudo chown -R $USER:$(id -gn $USER) C:\Users\User\.config │
└───────────────────────────────────────────────────────────┘

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\User\AppData\Roaming\npm-cache\_logs\2018-08-02T08_21_58_080Z-debug.log

-----------------------------------
What can I do to solve this problem?
My installed versions:
- expo: 29.0.0
- react: 16.3.1
- node: 10.7.0
- npm: 4.6.1

**Comment by EvanBacon** [comment]
https://github.com/expo/browser-polyfill/issues/7
