### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by Erenner** [expo/expo-three#62]
npm ERR! @expo/browser-polyfill@0.0.0-alpha.10 postinstall: `find ../ -name .babelrc -delete`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the @expo/browser-polyfill@0.0.0-alpha.10 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by sahvelety** [comment]
npm install --ignore-scripts

**Comment by EvanBacon** [comment]
fixed this in alpha.3 of `@expo/browser-polyfill`
