### ISSUE TITLE
Trying to use an Expo Three Raycaster but intersects are empty or wrong

### ISSUE THREAD

**Issue by adriaanbalt** [expo/expo-three#64]
I'm trying to intersect meshes with Three Raycaster but for some reason the default array of intersects is defaulting to 10 meshes and when I "touch" the intersects array becomes empty.  Does Raycaster not work with your version of THREE?  I investigated the NPM package, specifically it is [loading THREE ](https://github.com/expo/expo-three/blob/master/lib/Three.js) but when I look closer I don't see an instance of THREE inside `npm_modules`.  Here's the code

Snack:
https://snack.expo.io/@adriaanbalt/raycaster-using-expo-three

```js
import Expo from "expo";
import React from "react";
import { Dimensions, View, Animated, PanResponder } from "react-native";
import ExpoTHREE, { THREE } from "expo-three"; // 3.0.0-alpha.4

import MeshContainer from "./MeshContainer";

export default class App extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      pan: new Animated.ValueXY(),
      mouse: new THREE.Vector2(),
    };
    THREE.suppressExpoWarnings(true);
  }

  componentWillMount() {
    this._val = { x: 0, y: 0 };
    this.state.pan.addListener(value => (this._val = value));

    this.panResponder = PanResponder.create({
      onStartShouldSetPanResponder: (e, gesture) => true,
      onPanResponderGrant: (e, gesture) => {
        this.state.pan.setOffset({
          x: this._val.x,
          y: this._val.y
        });
        this.state.pan.setValue({ x: -1, y: -1 });
      },
      onPanResponderMove: ({ nativeEvent }, gestureState) => {
        this.state.mouse.x = nativeEvent.locationX;
        this.state.mouse.y = nativeEvent.locationY;
      },
    });

  }

  render() {
    return (
      <View
        {...this.panResponder.panHandlers}
        style={[
          {
            width: Dimensions.get("window").width,
            height: Dimensions.get("window").height
          }
        ]}
      >
        <Expo.GLView
          style={{ flex: 1 }}
          onContextCreate={this._onGLContextCreate}
        />
      </View>
    );
  }

  _onGLContextCreate = async gl => {
    const scene = new THREE.Scene();

    const raycaster = new THREE.Raycaster(); // is this correct?

    const camera = new THREE.PerspectiveCamera(
      100,
      gl.drawingBufferWidth / gl.drawingBufferHeight,
      1,
      10000
    );
    camera.position.z = 2;

    const renderer = new ExpoTHREE.Renderer({ gl });
    renderer.setSize(gl.drawingBufferWidth, gl.drawingBufferHeight);

    const Container = new MeshContainer();
    const containerMesh = Container.getMesh();
    scene.add(containerMesh);

    let objects = []
    objects.push(containerMesh);

    let INTERSECTED;

    const animate = p => {
      requestAnimationFrame(animate);

      raycaster.setFromCamera( this.state.mouse, camera );
      let intersects = raycaster.intersectObjects( objects );
      // let intersects = raycaster.intersectObjects( scene.children ); // this doesn't seem to make any difference

      console.log( 'intersects length: ', intersects.length ); // defaults to 10 before touch and after touch becomes 0
      
      if ( intersects.length > 0 ) {
            if ( INTERSECTED != intersects[ 0 ].object ) {
                INTERSECTED = intersects[ 0 ].object;
            }
        } else {
            INTERSECTED = null;
        }

      renderer.render(scene, camera);

      gl.endFrameEXP();
    };
    animate();
  };
}
```

MeshContainer.js
```js
import React from "react";
import ExpoTHREE, { THREE } from "expo-three"; // 3.0.0-alpha.4

export default class MeshContainer extends React.Component {

    constructor() {
        super();
        let geometry = new THREE.CircleGeometry(.25, 10);
        let material = new THREE.MeshBasicMaterial({
            color: 0xFF00FF,
            opacity: 1
        });
        this.mesh = new THREE.Mesh(geometry, material);
    }

    getMesh() {
        // this.mesh.superName = 'MovingLetter'
        return this.mesh
    }

}
```

**Comment by adriaanbalt** [comment]
it was due to this:

```js
onPanResponderMove: ({ nativeEvent }, gestureState) => {
    this.state.mouse.x = nativeEvent.locationX;
    this.state.mouse.y = nativeEvent.locationY;
}
```

it should have been:

```js
onPanResponderMove: ({ nativeEvent }, gestureState) => {
    if ( this.state.gl ) {
        this.state.mouse.x = (nativeEvent.locationX / this.state.gl.drawingBufferWidth) * 4 - 1;
        this.state.mouse.y = -(nativeEvent.locationY / this.state.gl.drawingBufferHeight) * 4 + 1;
    }
}
```

where I set `this.state.gl` as follows:
```js
_onGLContextCreate = async gl => {
    this.state.gl = gl;
    ...etc
}
```

**Comment by EvanBacon** [comment]
?? You shouldn't directly mutate a components state:
```js
this.setState({ gl });

// instead of 

this.state.gl = gl;
```
If you want to save the variable without updating the component, then use some other variable:

```js
this._gl = gl;
```

**Comment by nik-sloop** [comment]
I am having trouble getting this to work. Would either of you be able to help?

**Comment by adriaanbalt** [comment]
```js
import Expo from "expo";
import { GLView } from "expo-gl";
import ExpoTHREE, { THREE } from "expo-three"; // 3.0.0-alpha.4
import React from "react";
import { connect } from "react-redux";
import {
	View,
	Animated,
	Text,
	Dimensions,
	PanResponder,
} from "react-native";

const { height, width } = Dimensions.get("window");

class HomeScreen extends React.Component {

	constructor(props) {
		super(props);

		this.state = {
			pan: new Animated.ValueXY(),
			mouse: new THREE.Vector2(0, 0),
		};
		// Turn off extra warnings
		THREE.suppressExpoWarnings(true);
		// hide warnings yellow box in ios
		console.disableYellowBox = true;
	}

	componentWillMount() {
		this._val = { x: 0, y: 0 };
		this.state.pan.addListener((value) => (this._val = value));

		this.panResponder = PanResponder.create({
			onStartShouldSetPanResponder: (e, gesture) => true,
			onPanResponderGrant: (e, gesture) => {
				this.state.pan.setOffset({
					x: this._val.x,
					y: this._val.y,
				});
				this.state.pan.setValue({ x: 0, y: 0 });
			},
			onPanResponderMove: ({ nativeEvent }, gestureState) => {
				if (this.state.gl) {
					// ratio of mouse position to the width of the screen
					this.state.mouse.x =
						(nativeEvent.locationX / width) * 2 - 1;
					this.state.mouse.y =
						-(nativeEvent.locationY / height) * 2 + 1;
				}
			},
			onPanResponderRelease: ({ nativeEvent }, gestureState) => {
				this.state.mouse.x = 0;
				this.state.mouse.y = 0;
			},
		});
	}

	_onGLContextCreate = async (gl) => {
		const renderer = new ExpoTHREE.Renderer({ gl, depth: false });
		renderer.setPixelRatio(window.pixelRatio || 1);
		renderer.setSize(gl.drawingBufferWidth, gl.drawingBufferHeight);
		renderer.setClearColor(0x000000, 1.0);
		const camera = new THREE.PerspectiveCamera(
			100,
			gl.drawingBufferWidth / gl.drawingBufferHeight,
			0.1,
			20000,
		);
		camera.position.set(0, 0, 1.0).multiplyScalar(20);
		const raycaster = new THREE.Raycaster();
		const scene = new THREE.Scene();

		const yourMesh = // Your mesh
		scene.add(yourMesh);


		let intersects;

		const over = () => {
		};
		const out = () => {
		};

		const animate = (p) => {
			requestAnimationFrame(animate);

			camera.updateMatrixWorld();

			raycaster.setFromCamera(this.state.mouse, camera);
			intersects = raycaster.intersectObjects(scene.children, true);

			if (intersects.length > 0) {
				// OVER
                over()
			} else {
				// NOT OVER
                out()
			}

			renderer.render(scene, camera);

			gl.endFrameEXP();
		};

		animate();
	};

	render() {
		const { height, width } = Dimensions.get("window");
		return (
			<View
				{...this.panResponder.panHandlers}
				style={[
					{
						width,
						height,
					},
				]}>
				<GLView
					style={{ flex: 1 }}
					onContextCreate={this._onGLContextCreate}
				/>
			</View>
		);
	}

}

export default Screen```

This is where I ended up, give or take @nik-sloop 

I haven't compared this to what is above, but I've been using the above snippet (with some other stuff) in published apps on the app store.

**Comment by nik-sloop** [comment]
I got it to work with a simple cube mesh, but for some reason when I replace the cube with my loaded model (.obj) it does not work. Here is my code

`import { View as GraphicsView } from 'expo-graphics';
import ExpoTHREE, { THREE } from 'expo-three';
import React from 'react';
import Expo from 'expo';

import ExpoGraphics from 'expo-graphics';
import { PixelRatio } from 'react-native';
import {PanResponder, StyleSheet, Animated, Dimensions} from 'react-native';

import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader';
import { TouchableHighlight, TouchableOpacity } from 'react-native-gesture-handler';

const pageWidth = Dimensions.get('window').width;
const pageHeight = Dimensions.get('window').height*.75;

export default class Body extends React.Component {
  constructor(props) {
    super(props);
    
    this.mouse = new THREE.Vector2();
    
    this.direction = 1;
    this.lastDirection = 1;
    const panResponder = PanResponder.create({
      onStartShouldSetPanResponder: () => true,
      onPanResponderMove: ({ nativeEvent }, gesture) => {  
        /* console.log("Gesture X: "+gesture.x0);
        console.log("Gesture Y: "+gesture.y0);
        console.log("Native X: "+nativeEvent.locationX);
        console.log("Native Y: "+nativeEvent.locationY) */;
        /* if(this._gl){
          this.mouse.x = (nativeEvent.locationX / this._gl.drawingBufferWidth) * 4 -1;
          this.mouse.y = -(nativeEvent.locationY / this._gl.drawingBufferHeight) * 4 + 1;
        } */
        
        this.mouse.x = (nativeEvent.locationX / pageWidth) * 2 -1;
        this.mouse.y = -(nativeEvent.locationY / pageHeight) * 2 + 1;
        //console.log("X: " + this.mouse.x);
        //console.log("Y: " + this.mouse.y); 

        if(gesture.numberActiveTouches == 1){         
          if(gesture.dx < -5){          
            this.direction = (gesture.vx) * 1.1;
          }
          else if(gesture.dx > 5){
            this.direction =  (gesture.vx) * 1.1;
          } 
          else {
            this.direction = 0;
          } 
       }
      },
      onPanResponderRelease: (evt, gestureState) => {
        console.log("Release");
        this.mouse.x = -2;
        this.mouse.y = -2;
      },
   });
   this.state = { panResponder };
  }
  componentWillMount() {
    THREE.suppressExpoWarnings();  

  }
  //
  render() {
    return (
      <Animated.View style={styles.ball}  {...this.state.panResponder.panHandlers}>
        <ExpoGraphics.View 
        onContextCreate={this.onContextCreate} 
        onRender={this.onRender}
        />
      </Animated.View>
         
      
          
    );
  }
  // This is called by the `ExpoGraphics.View` once it's initialized
  onContextCreate = async ({
    gl,
    canvas,
    width,
    height,
    scale: pixelRatio,
  }) => {
    this._gl = gl;
    /* console.log("pixelRatio: " + pixelRatio);
    console.log("width: " + width);
    console.log("height: " + height);
    console.log("Page Width: " + pageWidth);
    console.log("Page Height: " + pageHeight); */
    this.raycaster = new THREE.Raycaster();
    const pr = pageWidth / pageHeight;
    console.log(gl.drawingBufferWidth);
    console.log(gl.drawingBufferHeight);
    // create renderer (The thing that shows the object)
    //this.renderer = new ExpoTHREE.Renderer({ gl, pr , pageWidth, pageHeight });
    //this.renderer.setClearColor(0xffffff);
    this.renderer = new ExpoTHREE.Renderer({ gl });
    this.renderer.setSize(gl.drawingBufferWidth,gl.drawingBufferHeight)
    // create a new scene (a place for the objects to be)
    this.scene = new THREE.Scene();

    //create the camera (the view through which the object is seen)
    //this.camera = new THREE.PerspectiveCamera(75, pageWidth / pageHeight, 0.1, 1000);
    this.camera = new THREE.PerspectiveCamera(100, gl.drawingBufferWidth / gl.drawingBufferHeight, 1, 10000);
    this.camera.position.z = 4;
    this.camera.position.y = 2.5;
   
    

    const model = {
      'person.obj': require('../../assets/objects/person.obj')
    };
    const mesh = await ExpoTHREE.loadAsync(model['person.obj']);
    var geoMesh = mesh.geometry; 
    var matMesh = mesh.material;
    var loader = new THREE.ObjectLoader();
    loader.load(model['person.obj'],(object) => {
      object.rotation.y = Math.PI;
      this.scene.add(object);
    });
    let geometry = new THREE.BoxGeometry(5,5,5);
    let material = new THREE.MeshBasicMaterial({
            color: 0xFF00FF,
            opacity: 1
        }); 
    this.cube = new THREE.Mesh(geometry,material);
    //this.mesh = new THREE.Mesh(geoMesh,matMesh);
    this.mesh = mesh;

    ExpoTHREE.utils.scaleLongestSideToSize(this.mesh, 5);
    ExpoTHREE.utils.alignMesh(this.mesh, { y: 1 });

    //this.scene.add(mesh);
    //this.scene.add(this.cube);

    this.scene.add(new THREE.AmbientLight(0x404040));

    const light = new THREE.DirectionalLight(0xffffff, 0.5);
    
    this.scene.add(light);
    
  };

  onRender = delta => {
    
    this.raycaster.setFromCamera( this.mouse, this.camera );
    
    var intersects = this.raycaster.intersectObjects( this.scene.children );

    
    //console.log("Number of Intersects: "+ intersects.length);
    this.cube.material.color.set(0xFF00FF);
    for (var i = 0; i < intersects.length; i++){
      console.log('TOUCHING!');
      intersects[i].object.material.color.set(0xFF0000);
    } 
    
    this.mesh.rotation.y += (.5) * delta;//(this.direction) * delta;
    this.cube.rotation.y += .5*delta;
    this.renderer.render(this.scene, this.camera);
    
    };
}
const styles = StyleSheet.create({
  ball: {
     height: Dimensions.get('window').height *.75,
     width: Dimensions.get('window').width,
     borderWidth: 1,       
  },
});`

**Comment by nik-sloop** [comment]
`import { View as GraphicsView } from "expo-graphics";
import ExpoTHREE, { THREE } from "expo-three";
import React from "react";
import Expo from "expo";

import ExpoGraphics from "expo-graphics";
import { PixelRatio } from "react-native";
import {PanResponder, StyleSheet, Animated, Dimensions} from "react-native";

import { GLTFLoader } from "three/examples/jsm/loaders/GLTFLoader";
import { TouchableHighlight, TouchableOpacity } from "react-native-gesture-handler";

const pageWidth = Dimensions.get("window").width;
const pageHeight = Dimensions.get("window").height*.75;

export default class Body extends React.Component {
  constructor(props) {
    super(props);
    
    this.mouse = new THREE.Vector2();
    
    this.direction = 1;
    this.lastDirection = 1;
    const panResponder = PanResponder.create({
      onStartShouldSetPanResponder: () => true,
      onPanResponderMove: ({ nativeEvent }, gesture) => {  
        /* console.log("Gesture X: "+gesture.x0);
        console.log("Gesture Y: "+gesture.y0);
        console.log("Native X: "+nativeEvent.locationX);
        console.log("Native Y: "+nativeEvent.locationY) */;
        /* if(this._gl){
          this.mouse.x = (nativeEvent.locationX / this._gl.drawingBufferWidth) * 4 -1;
          this.mouse.y = -(nativeEvent.locationY / this._gl.drawingBufferHeight) * 4 + 1;
        } */
        
        this.mouse.x = (nativeEvent.locationX / pageWidth) * 2 -1;
        this.mouse.y = -(nativeEvent.locationY / pageHeight) * 2 + 1;
        //console.log("X: " + this.mouse.x);
        //console.log("Y: " + this.mouse.y); 

        if(gesture.numberActiveTouches == 1){         
          if(gesture.dx < -5){          
            this.direction = (gesture.vx) * 1.1;
          }
          else if(gesture.dx > 5){
            this.direction =  (gesture.vx) * 1.1;
          } 
          else {
            this.direction = 0;
          } 
       }
      },
      onPanResponderRelease: (evt, gestureState) => {
        console.log("Release");
        this.mouse.x = -2;
        this.mouse.y = -2;
      },
   });
   this.state = { panResponder };
  }
  componentWillMount() {
    THREE.suppressExpoWarnings();  

  }
  //
  render() {
    return (
      <Animated.View style={styles.ball}  {...this.state.panResponder.panHandlers}>
        <ExpoGraphics.View 
        onContextCreate={this.onContextCreate} 
        onRender={this.onRender}
        />
      </Animated.View>
         
      
          
    );
  }
  // This is called by the `ExpoGraphics.View` once it"s initialized
  onContextCreate = async ({
    gl,
    canvas,
    width,
    height,
    scale: pixelRatio,
  }) => {
    this._gl = gl;
    /* console.log("pixelRatio: " + pixelRatio);
    console.log("width: " + width);
    console.log("height: " + height);
    console.log("Page Width: " + pageWidth);
    console.log("Page Height: " + pageHeight); */
    this.raycaster = new THREE.Raycaster();
    const pr = pageWidth / pageHeight;
    console.log(gl.drawingBufferWidth);
    console.log(gl.drawingBufferHeight);
    // create renderer (The thing that shows the object)
    //this.renderer = new ExpoTHREE.Renderer({ gl, pr , pageWidth, pageHeight });
    //this.renderer.setClearColor(0xffffff);
    this.renderer = new ExpoTHREE.Renderer({ gl });
    this.renderer.setSize(gl.drawingBufferWidth,gl.drawingBufferHeight)
    // create a new scene (a place for the objects to be)
    this.scene = new THREE.Scene();

    //create the camera (the view through which the object is seen)
    //this.camera = new THREE.PerspectiveCamera(75, pageWidth / pageHeight, 0.1, 1000);
    this.camera = new THREE.PerspectiveCamera(100, gl.drawingBufferWidth / gl.drawingBufferHeight, 1, 10000);
    this.camera.position.z = 4;
    this.camera.position.y = 2.5;
   
    

    const model = {
      "person.obj": require("../../assets/objects/person.obj")
    };
    const mesh = await ExpoTHREE.loadAsync(model["person.obj"]);
    var geoMesh = mesh.geometry; 
    var matMesh = mesh.material;
    var loader = new THREE.ObjectLoader();
    loader.load(model["person.obj"],(object) => {
      object.rotation.y = Math.PI;
      this.scene.add(object);
    });
    let geometry = new THREE.BoxGeometry(5,5,5);
    let material = new THREE.MeshBasicMaterial({
            color: 0xFF00FF,
            opacity: 1
        }); 
    this.cube = new THREE.Mesh(geometry,material);
    //this.mesh = new THREE.Mesh(geoMesh,matMesh);
    this.mesh = mesh;

    ExpoTHREE.utils.scaleLongestSideToSize(this.mesh, 5);
    ExpoTHREE.utils.alignMesh(this.mesh, { y: 1 });

    //this.scene.add(mesh);
    //this.scene.add(this.cube);

    this.scene.add(new THREE.AmbientLight(0x404040));

    const light = new THREE.DirectionalLight(0xffffff, 0.5);
    
    this.scene.add(light);
    
  };

  onRender = delta => {
    
    this.raycaster.setFromCamera( this.mouse, this.camera );
    
    var intersects = this.raycaster.intersectObjects( this.scene.children );

    
    //console.log("Number of Intersects: "+ intersects.length);
    this.cube.material.color.set(0xFF00FF);
    for (var i = 0; i < intersects.length; i++){
      console.log("TOUCHING!");
      intersects[i].object.material.color.set(0xFF0000);
    } 
    
    this.mesh.rotation.y += (.5) * delta;//(this.direction) * delta;
    this.cube.rotation.y += .5*delta;
    this.renderer.render(this.scene, this.camera);
    
    };
}
const styles = StyleSheet.create({
  ball: {
     height: Dimensions.get("window").height *.75,
     width: Dimensions.get("window").width,
     borderWidth: 1,       
  },
});`

**Comment by nik-sloop** [comment]
I am looking into it more and it seems like the imported model does not have a collider

**Comment by chira37** [comment]
> ```js
> import Expo from "expo";
> import { GLView } from "expo-gl";
> import ExpoTHREE, { THREE } from "expo-three"; // 3.0.0-alpha.4
> import React from "react";
> import { connect } from "react-redux";
> import {
> 	View,
> 	Animated,
> 	Text,
> 	Dimensions,
> 	PanResponder,
> } from "react-native";
> 
> const { height, width } = Dimensions.get("window");
> 
> class HomeScreen extends React.Component {
> 
> 	constructor(props) {
> 		super(props);
> 
> 		this.state = {
> 			pan: new Animated.ValueXY(),
> 			mouse: new THREE.Vector2(-10, -10), // -10 is to force the start position to be OFF the screen so the user isn't automatically ontop of something
> 		};
> 		// Turn off extra warnings
> 		THREE.suppressExpoWarnings(true);
> 		// hide warnings yellow box in ios
> 		console.disableYellowBox = true;
> 	}
> 
> 	componentWillMount() {
> 		this._val = { x: 0, y: 0 };
> 		this.state.pan.addListener((value) => (this._val = value));
> 
> 		this.panResponder = PanResponder.create({
> 			onStartShouldSetPanResponder: (e, gesture) => true,
> 			onPanResponderGrant: (e, gesture) => {
> 				this.state.pan.setOffset({
> 					x: this._val.x,
> 					y: this._val.y,
> 				});
> 				this.state.pan.setValue({ x: -10, y: -10 });
> 			},
> 			onPanResponderMove: ({ nativeEvent }, gestureState) => {
> 				if (this.state.gl) {
> 					// ratio of mouse position to the width of the screen
> 					this.state.mouse.x =
> 						(nativeEvent.locationX / width) * 2 - 1;
> 					this.state.mouse.y =
> 						-(nativeEvent.locationY / height) * 2 + 1;
> 				}
> 			},
> 			onPanResponderRelease: ({ nativeEvent }, gestureState) => {
> 				this.state.mouse.x = -10;
> 				this.state.mouse.y = -10;
> 			},
> 		});
> 	}
> 
> 	_onGLContextCreate = async (gl) => {
> 		const renderer = new ExpoTHREE.Renderer({ gl, depth: false });
> 		renderer.setPixelRatio(window.pixelRatio || 1);
> 		renderer.setSize(gl.drawingBufferWidth, gl.drawingBufferHeight);
> 		renderer.setClearColor(0x000000, 1.0);
> 		const camera = new THREE.PerspectiveCamera(
> 			100,
> 			gl.drawingBufferWidth / gl.drawingBufferHeight,
> 			0.1,
> 			20000,
> 		);
> 		camera.position.set(0, 0, 1.0).multiplyScalar(20);
> 		const raycaster = new THREE.Raycaster();
> 		const scene = new THREE.Scene();
> 
> 		const yourMesh = // Your mesh
> 		scene.add(yourMesh);
> 
> 
> 		let intersects;
> 
> 		const over = () => {
> 		};
> 		const out = () => {
> 		};
> 
> 		const animate = (p) => {
> 			requestAnimationFrame(animate);
> 
> 			camera.updateMatrixWorld();
> 
> 			raycaster.setFromCamera(this.state.mouse, camera);
> 			intersects = raycaster.intersectObjects(scene.children, true);
> 
> 			if (intersects.length > 0) {
> 				// OVER
>                 over()
> 			} else {
> 				// NOT OVER
>                 out()
> 			}
> 
> 			renderer.render(scene, camera);
> 
> 			gl.endFrameEXP();
> 		};
> 
> 		animate();
> 	};
> 
> 	render() {
> 		const { height, width } = Dimensions.get("window");
> 		return (
> 			<View
> 				{...this.panResponder.panHandlers}
> 				style={[
> 					{
> 						width,
> 						height,
> 					},
> 				]}>
> 				<GLView
> 					style={{ flex: 1 }}
> 					onContextCreate={this._onGLContextCreate}
> 				/>
> 			</View>
> 		);
> 	}
> 
> }
> 
> export default Screen
> ```
> 
> This is where I ended up, give or take @nik-sloop
> 
> I haven't compared this to what is above, but I've been using the above snippet (with some other stuff) in published apps on the app store.

This is working perfectly, save lots of time
Thanks👍👍👍
