### ISSUE TITLE
Font loading & SVG loading?

### ISSUE THREAD

**Issue by adriaanbalt** [expo/expo-three#65]
Any support for FontLoader?  I am unable to find relative paths using `Three.FontLoader()`
How about support for loading SVGs?

I've tried `loadAsync()`

**Comment by EvanBacon** [comment]
Try this out: https://snack.expo.io/@bacon/three-text
I always load the json in, then pass the json to the `FontLoader`. 
```js
const font = new THREE.FontLoader().parse(json)
```

But you could also load from a local uri like so:

```js
loadFontFromUri = async uri =>
    new Promise((res, rej) =>
      new THREE.FontLoader().load(uri, res, () => {}, rej),
    );
```

**Comment by adriaanbalt** [comment]
How about an SVG? @EvanBacon 
I found this but it barely works. https://snack.expo.io/@blamsoft/svg-loader-example
