### ISSUE TITLE
Doesn't work with expo-gl in vanilla react-native

### ISSUE THREAD

**Issue by flybayer** [expo/expo-three#66]
I am using `expo-gl` in a vanilla react-native project. I have this working on iOS with plain WebGL, but I want to use `expo-three`.

If I only install expo-three and three, Metro fails to build because it can't find the `expo` package.

After yarn install expo, it builds but I get this error:

<img width="654" alt="screen shot 2018-09-24 at 17 51 33" src="https://user-images.githubusercontent.com/8813276/45981319-8ce46700-c022-11e8-8492-5fef42206daf.png">

You can reproduce this error by checking out the `three` branch of this repo:
https://github.com/flybayer/TestExpoGL/tree/three
**Note:** Android isn't working with expo-gl yet on this test app

**Comment by smistert** [comment]
Hello, how did you create your project? did you use the expo-cli to generate the project?
I would think you need to add expo support to your project. Might be easier to generate a new project using expo init and then expo start to run your project. Have a look at https://expo.io/learn

**Comment by flybayer** [comment]
@smistert this was generated with react-native-cli. What I'm trying to do should be supported with the new universal modules feature. See https://github.com/expo/expo-gl/issues/2

**Comment by EvanBacon** [comment]
Closing as this is now resolved. Shopify even uses it in their latest app!
