### ISSUE TITLE
How to run example?

### ISSUE THREAD

**Issue by smartsoul** [expo/expo-three#70]
My steps:
1. Clone this repo.
2. Run 'npm i'
3. Run 'npm start'
4. Scan QR code.

**Result:** 
 [14:04:54] Unable to resolve "expo-react-native-adapter" from "node_modules\expo-core\index.js"
[14:04:54] Failed building JavaScript bundle.

Then I use npm to install 'expo-react-native-adapter'.

Reuslt:
The main scene shows up, but I click any samples, it pops up:
`TypeError: TypeError: undefined is not an object (evaluating '_require(_dependencyMap[0], './src/GLView').default')`

What should I do?

**Comment by smartsoul** [comment]
@EvanBacon Could you help to fix this problem?

**Comment by EvanBacon** [comment]
Couldn't recreate, just bumped to v30 of Expo and it's running fine. I also was able to get it running in v28.

**Comment by smartsoul** [comment]
I use 'yarn install' instead of 'npm install'.
It popup 'Couldn't find preset "es2015" relative to directory'.
I had to run "npm install --save-dev babel-preset-es2015" and config .babelrc file.
Then I can run the example.

@EvanBacon Thanks. It's nice to update it's dependencies.
