### ISSUE TITLE
Can't Install on sdkVersion 30.0.0

### ISSUE THREAD

**Issue by riftninja** [expo/expo-three#71]
1257 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
1258 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
1259 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
1259 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
1259 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   win32
1259 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
1260 verbose stack Error: @expo/browser-polyfill@0.0.0-alpha.10 postinstall: `find ../ -name .babelrc -delete`
1260 verbose stack Exit status 2
1260 verbose stack     at EventEmitter.<anonymous> (C:\Users\Default\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
1260 verbose stack     at emitTwo (events.js:126:13)
1260 verbose stack     at EventEmitter.emit (events.js:214:7)
1260 verbose stack     at ChildProcess.<anonymous> (C:\Users\Default\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
1260 verbose stack     at emitTwo (events.js:126:13)
1260 verbose stack     at ChildProcess.emit (events.js:214:7)
1260 verbose stack     at maybeClose (internal/child_process.js:925:16)
1260 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
1261 verbose pkgid @expo/browser-polyfill@0.0.0-alpha.10
1262 verbose cwd C:\Users\Default\ExpoProjects\nebmonster-scanner
1263 verbose Windows_NT 10.0.17134
1264 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Default\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "-S" "three" "expo-three"
1265 verbose node v8.9.4
1266 verbose npm  v6.4.1
1267 error code ELIFECYCLE
1268 error errno 2
1269 error @expo/browser-polyfill@0.0.0-alpha.10 postinstall: `find ../ -name .babelrc -delete`
1269 error Exit status 2
1270 error Failed at the @expo/browser-polyfill@0.0.0-alpha.10 postinstall script.
1270 error This is probably not a problem with npm. There is likely additional logging output above.
1271 verbose exit [ 2, true ]

**Comment by riftninja** [comment]
I've tried `npm i expo-three`, `npm i three expo-three` and `yarn add three expo-three`, keeps failing

**Comment by smartsoul** [comment]
I meet same issue. The reason is system need another 'find.exe' instead of widnows find.
1. Install cygwin.
2. Add 'C:\cygwin64\bin' to your path. And keep 'C:\cygwin64\bin' front.

I don't like this project. A lot of issues.

**Comment by riftninja** [comment]
@smartsoul thanks, seems that would have fixed the problem, ended up making a fork #72 and updated browser-polyfill dependency version. That fixed it for me.
