### ISSUE TITLE
Error: "npm ERR! path G:\GitProject\reactNative\expo\expo-three\expo-three-v3.0.0-alpha.4.tgz."

### ISSUE THREAD

**Issue by peacemind** [expo/expo-three#80]
When yarn from <Example> directory, I got this error 

"npm ERR! path G:\GitProject\reactNative\expo\expo-three\expo-three-v3.0.0-alpha.4.tgz"

I found the package.json file in the <Example> directory need to be update from 
"expo-three-v3.0.0-alpha.4.tgz" to "expo-three-v3.0.0-alpha.5.tgz" because the <EXPO-THREE> directory has "expo-three-v3.0.0-alpha.5.tgz".

**Comment by EvanBacon** [comment]
This is fixed in latest 5.5.1
