### ISSUE TITLE
loadDaeAsync Doesn't work on Android

### ISSUE THREAD

**Issue by akshayrao2** [expo/expo-three#85]
## Using ExpoTHREE loadDaeAsync function doesn't work in android.

**I have gone through all the issues but couldn't find any working solution for loading a model.** 

Calling the loadDaeAsync function internally calls multiple files and at last with the help of expo-asset-utils and expo-asset modules it downloads the model in local cache of android system and returns with setting downloaded flag as true and a localUri in the format 
`file:///data/user/0/three.app/cache/ExperienceData/%2540username2%252FthreeApp/ExponentAsset-4e8cc273339a196864faa0279fcd3569.dae`
this localUri is then loaded with the help of Fileloader.load function of three JS but unfortunately it always returns with an error from XMLHttpRequest for 
`unexpected url: file:///data/user/0/three.app/cache/ExperienceData/%2540username2%252FthreeApp/ExponentAsset-4e8cc273339a196864faa0279fcd3569.dae`

**NOTE: This works fine in IOS only having issue with Android.**

**Comment by EvanBacon** [comment]
This is due to a regression in React Native. You'll need to downgrade to Expo v30 to get the version of React Native with a functional fetch API.

**Comment by murat-mehmet** [comment]
> s is due to a regression in React Native. You'll need to downgrade to Expo v30 to get the version of React Native with a functional fetch API.

İs this even possible? I tried million ways and now that v33 is out, I found no way to use v30, it keeps asking to install expo-cli globally, then throws ENOENT error.. I'm unable to load any model format with animation at the moment...
