### ISSUE TITLE
Keeping Repo up to date with Three.js

### ISSUE THREAD

**Issue by wardjk87** [expo/expo-three#87]
First off, thanks for helping expo users bridge the gap between 3d technology and react-native.

I am wondering if there any plans to keep this project up to date with Three.js updates on a semi-routine basis? Three.js version .88 came out nov/2017.

Alternatively, would manually forking off and consuming a newer version of Three.js require a lot of work to synchronize with expo-three? In other words, would it be time consuming to do this manually?

I'm wondering, because I am learning three.js, and I have worked with react-native/ expo for over a year. I would like to make some mobile apps utilizing three.js and newer SDKs of expo. I want to be sure what I am learning can actually be implemented with expo-three.

**Comment by BamItsPixel** [comment]
@wardjk87 did you figure anything out? This is a great tool but we're currently 18 versions behind

**Comment by EvanBacon** [comment]
Three.js is now a peer dependency of expo-three
