### ISSUE TITLE
Unable to resolve .mtl and .obj file

### ISSUE THREAD

**Issue by ajdinahmetovic** [expo/expo-three#88]
I need to display a 3d model (.obj and wrap it with .jpg texture). I tried running your Snack for 'batman' example but i get error .mtl file is unable to resolve. I am using react native with expo. Is there working example of displaying basic 3D model. Thanks

**Comment by ajdinahmetovic** [comment]
Jus found solution for this.
It was failing to load .obj and .mtl files even tho I added assetExts to app.json. Then i made metro.config.js file where I added assetExts for .obj and .mtl files like this
module.exports = {
    resolver: {
        assetExts: ["db", "mp3", "ttf", "obj", "png", "jpg", "otf", "mtl"]
    }
};

and this made it WORKING

**Comment by rmib200** [comment]
Thanks, can confirm that this also resolved my issue!
