### ISSUE TITLE
how to use ShaderMaterial?

### ISSUE THREAD

**Issue by huangl7759** [expo/expo-three#9]
how to use ShaderMaterial as a  texture ? 
i do not want to use webgl apis.

**Comment by EvanBacon** [comment]
@huangl7759 you would use it exactly as it is listed in the [docs](https://threejs.org/docs/#api/materials/ShaderMaterial). 

---
**Here are a few Expo examples:**
- [Hatch Shader](https://github.com/EvanBacon/expo-three-demo/blob/adf8b77f6ecbcd6925c4c5cf7c5583d145839046/Scenes/HatchApp.js#L92-L107)
- [Toon Shader](https://github.com/EvanBacon/expo-three-demo/blob/adf8b77f6ecbcd6925c4c5cf7c5583d145839046/Scenes/ToonApp.js#L103-L108)
- [Sky Shader](https://github.com/EvanBacon/expo-three-demo/blob/771749d0cc7324dc1cb363855f670ed9aad338cc/assets/components/SkyShader.js#L204-L210)
- [All 10 from expo-three-demo](https://github.com/EvanBacon/expo-three-demo/search?utf8=%E2%9C%93&q=ShaderMaterial&type=): Note that some of these are broken
