### ISSUE TITLE
Standalone apps will not open

### ISSUE THREAD

**Issue by wardjk87** [expo/expo-three#90]
I built a 3d game using expo managed workflow and expo-three. I am using sdk 32 and latest expo-three version. I even tried ejecting the app but got the same result.

The app runs just fine on simulator and through the expo app. However when I build using expo build tool, the created apk and ipa will not open after downloaded to a device. The icon will not even display but only a greyed out design. Clicking on the app does nothing. However the app name does appear.

Ive tried multiple different changes to app.json to no affect. Originally I just used the initial app.json created with expo cli.

Has anyone tried or had issues making standalone apps using expo-three?

**Comment by alexandrius** [comment]
@wardjk87 Did you find any solution for this?

**Comment by wardjk87** [comment]
@alexandrius I spent about 6 frustrating hours trying during the course of a weekend, but I couldn't. I've been making expo/ react-native apps for 1.5 years including release 2 apps to the stores, so it's not like I haven't figured out problems in development before. 

Though given no response to the issue #87 that I posted, I'm not sure if this project is being adequately maintained by the expo team. I hope I am wrong, because I was really excited about making react-native games using expo-three. I've stopped working with expo-three for the time being, but I haven't given up hope for mobile three.js development. I may try again in the near future.

I may try to figure out another solution to using three.js and react-native to make an application that I can eventually upload to the stores. I don't want just an app that I only can use on the expo app. What are you using the library for?

**Comment by wardjk87** [comment]
I finally realized that I can't use I-Tunes 12.6 to install the ipa directly, because it won't work. I had to use application loader with X-code. I had to make sure I had the bundle Id registered with itunes connect. I then was able to use testflight to load the app on a device. It is working.
