### ISSUE TITLE
Unable to run example

### ISSUE THREAD

**Issue by psuslick** [expo/expo-three#99]
I'm attempting to run the example but am faced with dependency issues each time I try to build. My process below. Apologies in advance if the mistake is obvious. I greatly appreciate any support with getting this awesome resource working!

MacBook-Pro-4:example Phill$ npm install
npm WARN deprecated text-encoding@0.7.0: no longer maintained

> fsevents@1.2.9 install /Users/Phill/Downloads/expo-three-master-3/example/node_modules/fsevents
> node install

node-pre-gyp WARN Using needle for node-pre-gyp https download 
[fsevents] Success: "/Users/Phill/Downloads/expo-three-master-3/example/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node" is installed via remote
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN expo-graphics@1.1.0 requires a peer of expo@^32.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN expo-graphics@1.1.0 requires a peer of expo-gl@^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @expo/browser-polyfill@0.0.1-alpha.5 requires a peer of expo@^32.0.6 but none is installed. You must install peer dependencies yourself.
npm WARN @expo/browser-polyfill@0.0.1-alpha.5 requires a peer of react@^16.8.6 but none is installed. You must install peer dependencies yourself.
npm WARN react-native@0.55.4 requires a peer of react@16.3.1 but none is installed. You must install peer dependencies yourself.
npm WARN expo-asset@1.1.1 requires a peer of expo-file-system@~1.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN expo-core@1.2.0 requires a peer of expo-react-native-adapter@~1.2.0 but none is installed. You must install peer dependencies yourself.
npm WARN expo-payments-stripe@1.0.1 requires a peer of react@16.3.1 but none is installed. You must install peer dependencies yourself.
npm WARN react-native-maps@0.21.0 requires a peer of react-native@^0.51 || ^0.52 || ^0.53 || ^0.54 but none is installed. You must install peer dependencies yourself.
npm WARN react-native-reanimated@1.0.0-alpha.6 requires a peer of react@16.0.0-alpha.6 but none is installed. You must install peer dependencies yourself.
npm WARN react-native-reanimated@1.0.0-alpha.6 requires a peer of react-native@^0.44.1 but none is installed. You must install peer dependencies yourself.
npm WARN expo-asset-utils@1.1.1 requires a peer of expo-asset@~4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN expo-asset-utils@1.1.1 requires a peer of expo-file-system@~4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN expo-asset-utils@1.1.1 requires a peer of expo-font@~4.0.0 but none is installed. You must install peer dependencies yourself.

MacBook-Pro-4:example Phill$ npm install --save expo@30.0.0 @expo/browser-polyfill@0.0.1-alpha.3 expo-graphics@1.0.0-alpha.1 react@16.4.0 react-native@https://github.com/expo/react-native/archive/sdk-30.0.0.tar.gz react-navigation@2.3.0
npm WARN deprecated text-encoding@0.6.4: no longer maintained

> @expo/browser-polyfill@0.0.0-alpha.10 postinstall /Users/Phill/Downloads/expo-three-master-3/example/node_modules/expo-graphics/node_modules/@expo/browser-polyfill
> find ../ -name .babelrc -delete

npm WARN expo-asset-utils@1.1.1 requires a peer of expo-asset@~4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN expo-asset-utils@1.1.1 requires a peer of expo-file-system@~4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN expo-asset-utils@1.1.1 requires a peer of expo-font@~4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN expo-graphics@1.0.0-alpha.1 requires a peer of expo@^28.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @expo/browser-polyfill@0.0.0-alpha.10 requires a peer of expo@^28.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @expo/browser-polyfill@0.0.0-alpha.10 requires a peer of react@16.3.0 but none is installed. You must install peer dependencies yourself.
npm WARN @expo/browser-polyfill@0.0.1-alpha.3 requires a peer of expo@^28.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-native@0.55.4 requires a peer of react@16.3.1 but none is installed. You must install peer dependencies yourself.
npm WARN expo-react-native-adapter@1.2.0 requires a peer of react-native@^0.57.1 but none is installed. You must install peer dependencies yourself.
npm WARN expo-core@1.1.0 requires a peer of expo-react-native-adapter@~1.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-native-reanimated@1.0.0-alpha.6 requires a peer of react@16.0.0-alpha.6 but none is installed. You must install peer dependencies yourself.
npm WARN react-native-reanimated@1.0.0-alpha.6 requires a peer of react-native@^0.44.1 but none is installed. You must install peer dependencies yourself.
npm WARN react-native-maps@0.21.0 requires a peer of react-native@^0.51 || ^0.52 || ^0.53 || ^0.54 but none is installed. You must install peer dependencies yourself.

+ react@16.4.0
+ expo-graphics@1.0.0-alpha.1
+ expo@30.0.0
+ react-navigation@2.3.0
+ @expo/browser-polyfill@0.0.1-alpha.3
+ react-native@0.55.4
added 5 packages from 10 contributors, removed 6 packages and updated 41 packages in 32.152s
MacBook-Pro-4:example Phill$ expo start
┌─────────────────────────────────────────────────────────────┐
│                                                             │
│   There is a new version of expo-cli available (2.17.1).    │
│   You are currently using expo-cli 2.11.9                   │
│   Run `npm install -g expo-cli` to get the latest version   │
│                                                             │
└─────────────────────────────────────────────────────────────┘
Starting project at /Users/Phill/Downloads/expo-three-master-3/example
Expo DevTools is running at http://localhost:19002
Opening DevTools in the browser... (press shift-d to disable)
Starting Metro Bundler on port 19001.
Metro Bundler ready.
Tunnel ready.

  To run the app with live reloading, choose one of:
  • Sign in as @psuslick in Expo Client on Android or iOS. Your projects will automatically appear in the "Projects" tab.
  • Scan the QR code above with the Expo app (Android) or the Camera app (iOS).
  • Press a for Android emulator, or i for iOS simulator.
  • Press e to send a link to your phone with email/SMS.

Press ? to show a list of all available commands.
Logs for your project will appear below. Press Ctrl+C to exit.
**Unable to resolve "@expo/browser-polyfill" from "../build/ExpoTHREE.js"**
Failed building JavaScript bundle.
Building JavaScript bundle [=================================================================================================== ] 99%

**Comment by psuslick** [comment]
@EvanBacon Can you assist with this? Hopefully it is a simple oversight on my end.

**Comment by EvanBacon** [comment]
fixed in https://github.com/expo/expo-three/commit/7f95dc281816908c490459feb46426e92f8aec90
